#! /bin/bash
# Copyright the President and Fellows of Harvard College.
# Licensed under the MIT License

# Multiple exposure analysis -- take all of the previous *_allobjects.db files
# and run filter_multiple to extract all of the yet-unmatched star images, to
# see if we can derive an additional astrometric solution for them.
#
# This script used to be designed such that for solnum = 0, it was a noop; for
# solnum = 1, it would analyze the solnum = 0 data and emit a "none" database
# for solnum = 1, etc. This doesn't match well with the indexing used by the
# rest of the pipeline. Now, for solnum = 0 it analyzes the solnum = 0 data and
# emits the "none" database for solnum = 1, etc.
#
# Inputs:
#
# - ${DASCH_MATCH}/${series}${id}_${mosnum}_01${rot}ww_tnx.db
# - if solnum > 0:
#   - ${DASCH_INGEST}/${series}${id}_${mosnum}_01${rot}ww_s${np}_${qual}_allobjects.db
#     **for all 0 <= np < solnum**
# - if solnum = 0, this output is also an input (it is rewritten):
#   - ${DASCH_INGEST}/${series}${id}_${mosnum}_01${rot}ww${qual}_allobjects.db
#
# Outputs:
#
# - ${DASCH_ASTROMETRY}/${series}${id}_${mosnum}_01${rot}ww_s${solnum+1}_${qual}_none.db
#   - in rare circumstances, this doesn't get created
# - if solnum = 0, we back up the original allobjects.db:
#   - ${DASCH_INGEST}/${series}${id}_${mosnum}_01${rot}ww_s0_${qual}_allobjects.db
#     (backup of original allobjects)
#
# Database updates:
#
# - TBC
#
# Invokes:
#
# - filter_multiple
# - setFitWCS
#
# Variables used:
#
# - $DASCH_ASTROMETRY
# - $DASCH_INGEST
# - $DASCH_MATCH

if [ $# -eq 2 ] ; then
  qualifier=""
  qualcmd=""
elif [ $# -eq 3 ] ; then
  qualifier="_$3"
  qualcmd="-q $qualifier"
else
  echo "usage: $0 <solutionNumber> <list> [qualifier]"
  exit 1
fi

curSolutionNumber=$1
imagelist=$2

binning=16
((nextSolutionNumber=$curSolutionNumber + 1))

echo "Processing $imagelist"

for plate in $(cat $imagelist) ; do
  outputfile=${DASCH_ASTROMETRY}/${plate}_s${nextSolutionNumber}${qualifier}_none.db
  rm -f $outputfile

  sextrfile=${DASCH_MATCH}/${plate}_tnx.db
  if [ ! -e $sextrfile ] ; then
    echo "ERROR: Source extractor file $sextrfile does not exist"
    exit 1
  fi

  objfile0=${DASCH_INGEST}/${plate}${qualifier}_allobjects.db
  objfileb=${DASCH_INGEST}/${plate}_s0${qualifier}_allobjects.db
  filelist=$objfileb

  if [ -z "$qualifier" ] ; then
    if [ ! -e $objfile0 -a ! -e $objfileb ] ; then
      setFitWCS -e 0 -b NoAllobjects -p ${objfile0} -s
      echo "ERRORD: allobjects file (1) $objfile0 does not exist"
      exit 1
    fi

    setFitWCS -e 0 -b NoAllobjects -p ${objfile0} -c
  fi

  if [ "$qualifier" = apass ] ; then
    if [ ! -e $objfile0 && ! -e $objfileb ] ; then
      setFitWCS -e 0 -b NoAPASSAllobjects -p ${objfile0} -s
      echo "ERRORD: allobjects file (1) $objfile0 does not exist"
      exit 1
    fi

    setFitWCS -e 0 -b NoAPASSAllobjects -p ${objfile0} -c
  fi

  counter=1

  while [ $counter -lt $nextSolutionNumber ] ; do
    tmpfile=${DASCH_INGEST}/${plate}_s${counter}${qualifier}_allobjects.db

    if [ -e $tmpfile ] ; then
      if [ -z "$qualifier" ] ; then
        setFitWCS -e ${counter} -b NoAllobjects -p $tmpfile -c
      elif [ "$qualifier" = apass ] ; then
        setFitWCS -e ${counter} -b NoAPASSAllobjects -p $tmpfile -c
      fi
    else
      if [ -z "$qualifier" ] ; then
        setFitWCS -e ${counter} -b NoAllobjects -p $tmpfile -s
      elif [ "$qualifier" = apass ] ; then
        setFitWCS -e ${counter} -b NoAPASSAllobjects -p $tmpfile -s
      fi

      echo "allobjects file (2) $tmpfile does not exist"
      counter=0
      break
    fi

    filelist="$filelist $tmpfile"
    ((counter+=1))
  done

  echo "counter $counter, nextSolutionNumber $nextSolutionNumber"

  if [ $counter -ne $nextSolutionNumber ] ; then
    echo "ERROR: not all allobjects files found"
    exit 1
  fi

  #make a backup of the allobjects file if none exists

  if [ ! -e $objfileb ] ; then
    #if the allobjects file is not the original generated by recover_points, do not copy it
    testfile=$(head -n 1 $objfile0 |grep solutionNumber)

    if [ -z "$testfile" ] ; then
      echo "mv $objfile0 $objfileb"
      mv $objfile0 $objfileb
    fi
  fi

  set -x
  filter_multiple \
    -v \
    -e $nextSolutionNumber \
    $qualcmd \
    -b $binning \
    -a $objfile0 \
    -o $outputfile \
    -s $sextrfile \
    $filelist
  set +x

  if [ ! -e $outputfile ] ; then
    echo "NOTE: filter_multiple failed; no output $outputfile"
  fi
done

#  Apr 20, 2009 Edward J. Los - Initial version
#  May  1, 2009 Edward J. Los - Do not delete the "NONE" database if there was a success
#  Aug 28, 2009 Edward J. Los - Change _e to _s to reflect difference between solutionNumber and exposureNumber
#  Nov  3, 2009 Edward J. Los - Remove find_astrometry2.csh.  Save the initial _allobjects file prior to over-write.
#  Dec 16, 2009 Edward J. Los - Add SetFitWCS support to log pipeline status in the MySQL database.
#  Feb 26, 2012 Edward J. Los - Update for multiple exposures
#  Jun 27, 2010 Edward J. Los - Prevent use of a stale multiple exposure source list
#  Apr 15, 2014 Edward J. Los - Mark miscellaneous errors deferred with ERRORD
#  Oct 16, 2015 Edward J. Los - Support the NoAPASSAllobjects FitWCS bit
