#! /bin/bash
# Copyright the President and Fellows of Harvard College.
# Licensed under the MIT License

# Reformat the files produced by Sumin in MATLAB, combining the annular bin
# catalogs into a single catalog, which is Starbase compatible. Add new columns:
# spatial_bin, limiting_mag, magcal_iso_error. Note that error and limiting mag
# are the same for all stars in a given bin. Restore the proper formatting for
# the GSC2 star names in column "REF".
#
# It is possible that the `annular9` calibration may have failed for some of the
# spatial bins, in which case some of the inputs will be missing. This is OK.
# But if *none* of those calibrations worked, we have a problem.
#
# Inputs:
#
# - $DASCH_BINOUTPUT/${series}${id}_${mosnum}_01${rot}ww${sol_tag}${qual}_a{1..9}.grid
# - $DASCH_BINOUTPUT/${series}${id}_${mosnum}_01${rot}ww${sol_tag}${qual}_a{1..9}.out
# - $DASCH_BINOUTPUT/${series}${id}_${mosnum}_01${rot}ww${sol_tag}${qual}_a{1..9}.para
#
# Outputs:
#
# - $DASCH_INGEST/${series}${id}_${mosnum}_01${rot}ww${sol_tag}${qual}.out.db
# - $DASCH_INGEST/${series}${id}_${mosnum}_01${rot}ww${sol_tag}${qual}.out.db.ra.b
# - $DASCH_INGEST/${series}${id}_${mosnum}_01${rot}ww${sol_tag}${qual}.out.db.REF.i
# - $DASCH_INGEST/${series}${id}_${mosnum}_01${rot}ww${sol_tag}${qual}.out.db.dec.i
# - $DASCH_INGEST/${series}${id}_${mosnum}_01${rot}ww${sol_tag}${qual}.out.spatial_bins.db
# - ~DELETES~ $DASCH_BINOUTPUT/${series}${id}_${mosnum}_01${rot}ww${sol_tag}${qual}.annular9_marker.txt
#
# Database updates: none.
#
# External dependencies:
#
# - Starbase (index)
#
# Variables used:
#
# - $DASCH_BINOUTPUT
# - $DASCH_INGEST
# - $DASCH_SCRIPTS

solutionNumber=$1
imagelist=$2

if [ $# -eq 2 ] ; then
  qualifier=""
elif [ $# -eq 3 ] ; then
  qualifier="_$3"
else
  echo "usage: $0 <solutionNumber> <list> [qualifier]"
  echo "  solutionNumber is the multiple exposure iteration"
  echo "  list      is the list of mosaics to process"
  echo "  qualifier is a string append to output filenames"
  exit 1
fi

if [ $solutionNumber -eq 0 ] ; then
  solutionString=""
else
  solutionString="_s$solutionNumber"
fi

# Definition of columns:  *.out: 18 columns: 1:REF; 2:ra; 3:dec; 4:B mag;
# 5:color; 6:iso; 7:NUMBER, 8:BFLAGS, 9: X_IMAGE, 10: Y_IMAGE, 11:ddec; 12:dra
# 13: extinction  14: spatial_bin 15: local_bin 16:fitted magnitude,17: fitted
# mag - B mag, 18: Smoothed RMS only the last three columns are fitting results
# We will add spatial_bin and limiting_mag, but remove ddec and dra

columns="REF ra dec refmag color MAG_ISO NUMBER BFLAGS X_IMAGE Y_IMAGE extinction spatial_bin local_bin magcal_iso dmag_iso magcal_iso_rms limiting_mag max_bright_mag"
work=$(mktemp -d)
echo $columns >$work/matlabheader.tmp
echo $columns |sed 's/[A-Za-z_0-9]/-/g' >>$work/matlabheader.tmp

echo "Processing $imagelist"

for listentry in $(cat $imagelist) ; do
  cd $DASCH_INGEST

  plate="$DASCH_BINOUTPUT/${listentry}${solutionString}"
  echo $plate

  markerfile="${plate}${qualifier}.annular9_marker.txt"
  if [ -e $markerfile ] ; then
    rm $markerfile
  else
    echo "ERROR: annular9.m marker file $markerfile does not exist"
  fi

  scan=${listentry}${solutionString}${qualifier}.out
  para=${listentry}${solutionString}${qualifier}.para
  rm -f $scan
  touch $scan
  rm -f $para
  touch $para
  rm -f ${scan}.spatial_bins.db
  rm -f ${scan}.db

  sbin=0
  nbin=0

  catalog=$(shopt -s nullglob; echo ${plate}${qualifier}_a?.out)

  if [ -n "$catalog" ] ; then
    for catalog in ${plate}${qualifier}_a?.out ; do
      ((sbin+=1))
    done

    echo "spatial_bin" >$work/spatial_bin_definition.tmp
    echo "-----------" >>$work/spatial_bin_definition.tmp

    for bin in 1 2 3 4 5 6 7 8 9 ; do
      catalog="${plate}${qualifier}_a${bin}.out"
      catpara=$(echo $catalog |sed -e s/\\.out\$/.para/)

      if [ -e $catalog ] ; then
        ((nbin+=1))
        maglimit=$(awk '{print $1}' <$catpara)
        max_bright_mag=$(awk '{print $5}' <$catpara)
        cat $catalog |sed "s/\$/ ${maglimit} ${max_bright_mag}  /" >>$scan
        # collect the *.para files which record the limiting magnitude in each spatial bin
        parameters=$(cat $catpara)
        echo $parameters >>$para
        echo $bin >>$work/spatial_bin_definition.tmp
      fi
    done

    if [ $sbin -ne $nbin ] ; then
        echo "ERROR number of bins $nbin does not equal the number of files $sbin"
        exit
    fi

    echo $sbin spatial bins found ${listentry}${solutionString}

    # The REF column generated by Octave is now correct.
    # Here we eminate drad and ddec to reduce our columns from 20 to 18
    cat $scan \
      |awk '{print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$13,$14,$15,$16,$17,$18,$19,$20}' \
      >$work/refdata.tmp

    cat $work/matlabheader.tmp $work/refdata.tmp \
      |awk '{OFS="\t"}{print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18}' \
      >${scan}.db

    index -mb -n ${scan}.db ra
    index -mi -n ${scan}.db dec
    index -mi -n ${scan}.db REF

    # Just add the bin number to the parameters file

    echo "limiting_mag rms n1 n2 max_bright_mag max_bright_iso limiting_iso upper_limit colorterm errorcolor colorflag" >$work/para.header
    echo "------------ --- -- -- -------------- -------------- ------------ ----------- --------- ---------- ---------" >>$work/para.header
    cat $work/para.header $para >$work/para2.tmp

    paste $work/spatial_bin_definition.tmp $work/para2.tmp \
      |awk '{OFS="\t"}{print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12}' \
      >${scan}.spatial_bins.db

    rm $scan
    rm $para
    rm $work/refdata.tmp
    rm $work/para2.tmp
    rm $work/para.header
    rm $work/spatial_bin_definition.tmp
  else
    echo "0 spatial bins found: ${listentry}${solutionString}"
    # Signal a managed failure
    exit 31
  fi
done

rm -rf $work

# Oct 05, 2007 Edward J. Los.  Remove the addition of "N" to the REF column, since this
#                              column is now correct.
# Oct 09, 2007 Edward J. Los.  Find bins even if bin 1 has no data.
# Nov  6, 2007 Edward J. Los - Remove directory references and use environment variables instead
# Dec 11, 2007 Edward J. Los - Add NUMBER and FLAGS columns
# Dec 29, 2007 Edward J. Los - Support recalibrated GSC magnitudes.
# Jan 22, 2007 Edward J. Los - Add X_IMAGE and Y_IMAGE columns
#                              Add max_bright_mag (octave refmag4crit) to param
#                              Add max_bright_iso (octave iso4scrit) to param
#                              Add limiting_iso (octave isopointa) to param
#                              Remove plate_dist_min ra_min dec_min plate_dist_max ra_max dec_max
#                              because X_IMAGE and Y_IMAGE will provide the bins.
#                              Substitute per-star smoothed RMS for the full bin RMS from the parameter file
#                               (magcal_iso_error is replaced by magcal_iso_rms)
#                              Correct the spatial bin number when bins are missing
# Mar  5, 2007 Edward J. Los - Add a column for extinction
# Mar 28, 2008 Edward J. Los - Remove MAG_APER, ISOAREA, and plate_dist for performance
# Mar 31, 2008 Edward J. Los - drad should be dra
# Apr 19, 2008 Edward J. Los - remove stale output files
# Oct 21, 2008 Edward J. Los - add upper_limit
# Dec 12, 2008 Edward J. Los - add colorterm
# Jan 27, 2009 Edward J. Los - split FLAGS into AFLAGS and BFLAGS
# Sep 29, 2009 Edward J. Los - add multiple exposure support
# Mar 15, 2010 Edward J. Los - Check to see if annular9.m completed
# Mar 11, 2011 Edward J. Los - Add max_bright_mag to the output
# Mar 14, 2011 Edward J. Los - Add spatial_bin and local_bin to the output
