# Copyright the President and Fellows of Harvard College.
# Licensed under the MIT License

rm lowess.o
rm histc.o
rm lowess.oct
rm histc.oct
rm *.tmp
rm *.log
rm *_copylist.csh
rm *_copyback.csh
rm *.xxx
rm *.ra.dec.b
rm *.REF-b
rm cscope.out
rm cscope.files
rm find_drad.db
rm contour_plot_clip_smooth_correct2
rm assign_spatial_bins_2
rm scarglefast_SFS2
rm find_periods
rm fold 
rm pdm_freq
rm foldflags
rm octave-core
rm restoretan
rm juliandate
rm getdirectory
rm runpipeline
rm filterblended
rm getlocation
rm computemag
rm pipelineutils.o
rm photometryutils.o
rm searchgsc.o
rm scanread.o
rm RA2fpix.o
rm urlencode.o
rm magdeputil.o
rm urlencode
rm pipelineutils.a
rm pipelineutils
rm pgplot.ps
rm binpoints.ps
rm contour_plot
rm contour_plot_old
rm recover_points
rm find_drad2
rm find_drad3
rm find_drad4
rm find_drad5
rm prepare_octave
rm extract_lightcurves
rm formatgsc
rm matchstars
rm db2xyls
rm dumpxyls
rm getseries
rm filter_wedge
rm filter_defect
rm filter_ccmap
rm update_sextractor
rm find_distortion
rm showflags
rm showbins
rm matchtycho2
rm update_photometry
rm compare_colorterm
rm filter_multiple
rm update_summary
rm update_summary2
rm estimate_lightcurves
rm matchgsc
rm testtimer
rm plot_limiting
rm find_lightcurves
rm check_photometry
rm gridlimit
rm testmagiso
rm create_partitions
rm testkepler
rm search_none
rm formatkepler
rm matchcatalogs
rm filetest
rm dumpbin
rm setFitWCS
rm setPlateQuality
rm votable
rm web_edit
rm web_query
rm web_query_proto
rm web_plot
rm web_data
rm web_plot_proto
rm web_point
rm web_authorize
rm web_queue
rm dasch_scat
rm plot_multiple
rm setScampRMS
rm sourcelists.pyc
rm formatucac3
rm formatucac4
rm formatucac5
rm formatyb6
rm find_calibration
rm formatapass
rm formattycho2
rm checksize
rm comparefits
rm start.txt
rm copypipeline
rm magdepcalibrate
rm runfpack
rm search_close
rm search_close2
rm search_close3
rm clean_all.xxx
rm getscale
rm kdtree.o
rm add_galactic
rm resort_magfiles
rm formatvsx
rm formatsdss
rm update_limiting
rm galaxyutils.o
rm plothammer
rm dumplimitingbin
rm createregion
rm matchucac4
rm filterdr1
rm idstats
rm parselogs
rm parselogs2
rm parsescratchlog
rm plotmisc
rm tclstub.o
rm filter_scratch
rm checkdeletedplates
rm parseidtable
rm plottransient.o
rm plottransientstub.o
rm parse_coo.o
rm parse_coostub.o
rm formatgaia
rm formatcatalog
rm update_quality
rm check_colorterm
rm parseyield
rm parsebacula
rm combine_photometry
rm formatgaia2
rm mysqlstub.o
rm mapdistortion
rm sortplatelist
rm fix_stacksdb
rm formatatlas
rm parsesearch
rm convertjpeg
rm formatapass10
rm parsephot
rm multastrometry
rm parseplateimage
