# Copyright the President and Fellows of Harvard College.
# Licensed under the MIT License

#
#  find_drad.csh  This script examines results of the second
#  matching attempt to the star catalog using the "drad" field
#  generated by dasch_match.csh.  "drad" is the difference between
#  the Sextractor position and the catalog position in arcseconds.
#
#  The program builds a database, find_drad.db with the following
#  columns:
#          Series
#          Plate scale in arcsec/pixel
#          Radius of bin 1 in degrees
#          RMS_0 of drad for the entire plate
#          RMS_0 of drad for bin 1
#
#  Dec  5, 2007 Edward J. Los - Initial version
#  Dec 20, 2007 Edward J. Los - Reject stars if FLAGS >= 65536
#  Jan 28, 2009 Edward J. Los - Split FLAGS into AFLAGS and BFLAGS
#


set imagelist = $1
set catalog = $DASCH_CATALOG
set scripts = $DASCH_SCRIPTS
set completedFlag = `echo "$DASCH_COMPLETED" | wc -c`
if (-e find_drad.db) then
  rm find_drad.db
endif
   echo "plate series scale RMS A1RMS" >! find_drad.tmp
   echo "----- ------ ----- --- -----" >> find_drad.tmp


echo "Processing $imagelist"
foreach plate ( `cat $imagelist` ) 
#  set name = `echo $plate | sed 's/_tnx.fits//g'`
  set name = $plate
  if ($completedFlag > 2) then
    set filename = ${DASCH_COMPLETED}/match_${plate}_tnx_u.db
  else
    set directory = `$DASCH_SCRIPTS/getdirectory $plate`
    set filename = ${directory}/match_${plate}_tnx_u.db
  endif
  set platelocation = `$DASCH_SCRIPTS/getlocation -s $plate`
  set series = `echo "$platelocation" | gawk '{print $1}'`
  set scale  = `echo "$platelocation" | gawk '{print $2}'`
  set radius = `echo "$platelocation" | gawk '{print $3}'`
 

    set result1 = `row -i $filename 'AFLAGS < 1'  | column drad | statstable | grep RMS_0`
    set conditions = "(AFLAGS < 1) && (plate_dist < $radius)"
    set result2 = `row -i $filename "$conditions"  | column drad | statstable | grep RMS_0`
    set error1 = `echo "$result1" | gawk '{print $2}'`
    set error2 = `echo "$result2" | gawk '{print $2}'`
    echo "$plate  $scale $radius $error1 $error2"
    echo "$plate $series $scale $error1 $error2" >> find_drad.tmp

end
cat find_drad.tmp | gawk '{OFS="\t"}{print $1,$2,$3,$4,$5}' >! find_drad.db
rm find_drad.tmp
