// Copyright the President and Fellows of Harvard College.
// Licensed under the MIT License

/* formatgsc.c
 *
 * Read a starbase-formatted GSC2.3.2 extract generated by a dump of the compressed gsc2.3.2 catalog
 *
 *  1.  Compress the catalog using /dasch/apps/temp/cnvgsc2.cpp
 *  2.  Dump the compressed catalog triangles into a single starbase file:
 *      gsc23dasch -m2 19.0 -dump /dasch/raid008/CmpGsc/N0/00/00/N0000000.fit >! /dasch/Pipeline/catalogs/gsc232bin.db
 *      gsc23dasch -m2 19.0 -nohead -dump /dasch/raid008/CmpGsc/N0/00/00/N0000001.fit >> /dasch/Pipeline/catalogs/gsc232bin.db
 *      gsc23dasch -m2 19.0 -nohead -dump /dasch/raid008/CmpGsc/N0/00/00/N0000002.fit >> /dasch/Pipeline/catalogs/gsc232bin.db
 *      gsc23dasch -m2 19.0 -nohead -dump /dasch/raid008/CmpGsc/N0/00/00/N0000003.fit >> /dasch/Pipeline/catalogs/gsc232bin.db
 *      ... (for all 32768 files)    
 *  3.  Sort the results into 0.01 degree bins:
 *      
 *      index -mb -n gsc232bin.db dec
 *
 *  4.  Run formatgsc to put this file in binary format and to index it
 *      
 *      formatgsc  /dasch/Pipeline/catalogs/gsc232bin.db
 * 
 *      For statistics only:
 *      echo "formatgsc -s /dasch/Pipeline/catalogs/gsc232bin.db" | at now
 *       
 *
 * cc -ggdb -O2   -DLinux -DSTDC_HEADERS=1 -DCONFIG_BROKETS -DHAVE_DIRENT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_MEMCPY=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_FCNTL_H=1 -DHAVE_ALLOCA_H=1 -DHAVE_FLOAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MEMCHR=1 -DHAVE_STRCHR=1 -DHAVE_STRERROR=1 -DHAVE_STRUCT_TM_TM_ZONE=1 -DHAVE_TM_ZONE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -I /dasch/install/include  -L /dasch/install/lib -lm formatgsc.c pipelineutils.a  -ltable -lutil -lwcs  -L/usr/lib64/mysql -lmysqlclient -o formatgsc
 * 
 *
 *
 * Apr  1, 2008 Edward J. Los - Initial version
 * Jan 22, 2009 Edward J. Los - Add RaPM and DecPM, the proper motions in mas/yr.
 * May 23, 2009 Edward J. Los - Add statistics capability
 * May 17, 2009 Edward J. Los - Allow multiple GSC bin index sizes
 * May 29, 2009 Edward J. Los - Find the maximum GSC ID length
 * Jun 30, 2010 Edward J. Los - Generate a coverage plot file /dasch/scanner/linux/gmt/XXXXXX.txt where XXXXXX is the catalog file name.
 * Mar 24, 2011 Edward J. Los - Add -r <search radius> to eliminate duplicates.
 * Apr 11, 2011 Edward J. Los - Add 'q' for apass specific processing
 * Aug 17, 2011 Edward J. Los - Handle combined APASS and Tycho-2 catalog.
 * Nov 21, 2012 Edward J. Los - Add 'p' qualifier to give APASS priority and make all other catalogs placeholder variables
 * Aug 26, 2013 Edward J. Los - Add an 'o' qualifier to avoid a conflict with output file naming
 * Jun 24, 2014 Edward J. Los - Handle APASS colors
 * Feb  7, 2018 Edward J. Los - Remove references to stderr
 * Mar 10, 2018 Edward J. Los - Correct error statment formats
 * May 25, 2018 Edward J. Los - Handle RA >= 360.0 degrees, which first appears in the UCAC5 catalog.
 */   


#include <math.h>
#include <time.h>
#include "table.h"
#include "pipelineutils.h"

#include <errno.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include "libwcs/fitsfile.h"
#include "libwcs/wcs.h"

#define MAX_MASTER_NAME 512


#define MAGBASE  19.0  /* Base of the magnitude bins */
#define MAGINC    0.1  /* Resolution of the magnitude bins */
#define MAGBINS  250   /* Number of magnitude bins: good to mag -6.0 */
#define COLORINDEX_GSC   0    /* GSC color substition JPGMAG and FPGMAG */
#define COLORINDEX_TYCHO 1    /* BMAG and VMAG color substition */
#define COLORINDEX_NEITHER 2
#define COLORINDEX_MAX 3
#define MAX_BUFFER 1

extern GSCBIN gscBin64;
extern GSCBIN gscBin01;
PGSCBIN pGscBin64 = &gscBin64;
PGSCBIN pGscBin01 = &gscBin01;

double wcsdist(	/* Compute angular distance between 2 sky positions */
               double ra1,	/* First longitude/right ascension in degrees */
               double dec1,	/* First latitude/declination in degrees */
               double ra2,	/* Second longitude/right ascension in degrees */
               double dec2);	/* Second latitude/declination in degrees */


/* #define LOS_DEBUG 1 */  

int magcount[COLORINDEX_MAX][MAGBINS];
double avecolor[COLORINDEX_MAX][MAGBINS];
double magnorm[COLORINDEX_MAX][MAGBINS];
int maxcount[COLORINDEX_MAX];
int allcount[COLORINDEX_MAX];
int casetable[17];
FILE *mergeHandle = NULL;

int ReadMaster(PGSCAPASSIMAGE pMaster,
               File master_handle,
               TableHead master_header,
               TblDescriptor master_descriptor,
							 int sigmaPMPresent,
               int griPresent,
               TableRow* master_row)
{
	GSCIMAGEC masterC;
	PGSCIMAGEC pMasterC = &masterC;
	int nvals;
	char REF[MAX_REF];
	int refType;
	long long REFNumber;
  /* Initialize fields to defaults */
  memset(pMasterC,0,sizeof(GSCIMAGEC));
  memset(pMaster,0,sizeof(GSCAPASSIMAGE));
  pMaster->ra = 999.0;
  pMaster->dec = 99.0;
  pMaster->Stdmag = 99.999;
  pMaster->color = 9.999;
  pMaster->gmag = 99.999;
  pMaster->rmag = 99.999;
  pMaster->imag = 99.999;
  pMaster->vmagerr = 9.999;
  pMaster->bmagerr = 9.999;
  pMaster->gmagerr = 9.999;
  pMaster->rmagerr = 9.999;
  pMaster->imagerr = 9.999;


  *master_row = table_rowget(master_handle,master_header,*master_row,NULL,NULL,0);
  if (*master_row == NULL) {
    return(0);
  }
  if (!table_loadrow(master_handle,master_header,*master_row,master_descriptor,(char *)pMasterC)) {
    printf("ERROR: Read Master table_loadrow failed\n");
    return(0);
  }
	pMaster->REFNumber = 0;
	if ((pMasterC->REFNumber[0] == 'N') || (pMasterC->REFNumber[0] == 'S')) {
		if (GetREFNumber(pMasterC->REFNumber,&pMaster->REFNumber,&refType,0,0) != 0) {
			printf("ERROR: formatgsc invalid REFNumber '%s'\n",pMasterC->REFNumber);
			exit(-1);
		}
	} else {

		nvals = sscanf(pMasterC->REFNumber,"%lld",&pMaster->REFNumber);
		if ((nvals != 1) || (pMaster->REFNumber == 0)) {
			printf("ERROR: formatgsc failed to decode REFNumber '%s' at ra %d dec %d\n",pMasterC->REFNumber,pMasterC->ra,pMasterC->dec);
			exit(-1);
		}
		GetREF(pMaster->REFNumber,REF,1,1);
		if (GetREFNumber(REF,&REFNumber,&refType,0,0) != 0) {
			printf("ERROR: formatgsc invalid REF %s\n",REF);
			exit(-1);
		}
	}

	pMaster->ra = pMasterC->ra;
	pMaster->dec = pMasterC->dec;
	pMaster->Stdmag = pMasterC->Stdmag;
	pMaster->color = pMasterC->color;
	pMaster->RaPM = pMasterC->RaPM;
	pMaster->DecPM = pMasterC->DecPM;
	if (sigmaPMPresent) {
		pMaster->RaSigmaPM = pMasterC->RaSigmaPM;
		pMaster->DecSigmaPM = pMasterC->DecSigmaPM;
	} else {
		pMaster->RaSigmaPM = 0;
		pMaster->DecSigmaPM = 0;
	}
  if (griPresent) {
    pMaster->gmag = pMasterC->gmag;
    pMaster->rmag = pMasterC->rmag;
    pMaster->imag = pMasterC->imag;
    pMaster->vmagerr = pMasterC->vmagerr;
    pMaster->bmagerr = pMasterC->bmagerr;
    pMaster->gmagerr = pMasterC->gmagerr;
    pMaster->rmagerr = pMasterC->rmagerr;
    pMaster->imagerr = pMasterC->imagerr;
  } else {
    pMaster->gmag = 99.999;
    pMaster->rmag = 99.999;
    pMaster->imag = 99.999;
    pMaster->vmagerr = 9.999;
    pMaster->bmagerr = 9.999;
    pMaster->gmagerr = 9.999;
    pMaster->rmagerr = 9.999;
    pMaster->imagerr = 9.999;
  }
	pMaster->class = pMasterC->class;
	pMaster->VFlag = pMasterC->VFlag;
	pMaster->MAGFlag = pMasterC->MAGFlag;
	pMaster->flag = refType;
  return(1);

}


void FindBinError(double ra,double dec,int binNumber,double *pMaxRaError,double *pMaxDecError)
{
  double curMaxRaError = *pMaxRaError;
  double curMaxDecError = *pMaxDecError;
  double edgeRa;
  double edgeDec;
  int ra_bin;
  int dec_bin;
  int ra_num_bins;
  double curRaError = 0;
  double curDecError = 0;
  PBININDEX pBinIndex;
  PBININDEX pNextBin;

  pBinIndex = GetSubbins(pGscBin64,binNumber,&ra_bin,&dec_bin,"formatgsc");
  /* Lower left */
  edgeDec = pBinIndex->declination;
  edgeRa = ((360.00 * ra_bin)/pBinIndex->numBins);
  curDecError = edgeDec-dec;
  curRaError = edgeRa-ra;
  if (ra_bin == 0) {
    curRaError = 360.0 - ra;
  } 
  if (curDecError > curMaxDecError) {
    curMaxDecError = curDecError;
  }
  if (curRaError > curMaxRaError) {
    curMaxRaError = curRaError;
  }
  /* Upper */
  if (binNumber != (pGscBin64->dec_bins-1)) {
    pNextBin = &pGscBin64->pBinMasterIndex[dec_bin+1];
    edgeDec = pNextBin->declination;
    curDecError = dec-edgeDec;
    if (curDecError > curMaxDecError) {
      curMaxDecError = curDecError;
    }
  }
  /* Right */
  if (ra_bin == (pBinIndex->numBins -1)) {
    curRaError = ra;
  } else {
    edgeRa = ((360.00 * (ra_bin+1))/pBinIndex->numBins);
    curRaError = ra-edgeRa;
    if (curRaError > curMaxRaError) {
      curMaxRaError = curRaError;
    }
  }
  if (curRaError > *pMaxRaError) {
    *pMaxRaError = curRaError;
  }
  if (curDecError > *pMaxDecError) {
    *pMaxDecError = curDecError;
  }

         

}

/* Sort routine based on the right ascension */
int ImageCompare(const void *first, const void *second) 
{
  double numberFirst = ((PGSCAPASSIMAGE)first)->ra;
  double numberSecond = ((PGSCAPASSIMAGE)second)->ra;
  if (numberFirst > numberSecond) {
    return(1);
  } else if (numberFirst < numberSecond) {
    return(-1);
  } else {
    return(0);
  }
}
void RejectPlaceHolderDuplicate(PGSCAPASSIMAGE pSearch1, PGSCAPASSIMAGE pSearch2,PGSCAPASSIMAGE pSortMaster,int sortArraySize,int *pCurIndex,int searchIndex) {
  /* We go by the following truth table to select pSearch1 or pSearch2 */
  /* "A" means APASS "G" means GSC, "T" means Tycho2   "O" means GSC or Tycho2 */
  /*      Catalog    good RMS            */
  /*     S1   S2    S1   S2              */
  /*  1   G    G               Brightest */
  /*  2   T    T               Brightest */
  /*  3   T    G                  S1     */
  /*  4   G    T                  S2     */
  /*  8   O    A    -    -        S2     */
  /* 12   A    O    -    -        S1     */
  /* 13   A    A    OK   OK    Lowest RMS*/
  /* 14   A    A    OK   V        S1     */
  /* 15   A    A    V    OK       S2     */
  /* 16   A    A    V    V     Lowest RMS*/
  int curIndex = *pCurIndex;
  int selectSearch1 = 0;
  int selectLowRMS  = 0;
  int caseNumber = 0;
  PGSCAPASSIMAGE pSelected = pSearch2;
  PGSCAPASSIMAGE pRejected = pSearch1;
  int copyIndex;
  PGSCAPASSIMAGE pSearch3;
	char selectedREF[MAX_REF];
	char rejectedREF[MAX_REF];

  if ((pSearch1->flag == REF_TYPE_GSC) &&
      (pSearch2->flag == REF_TYPE_GSC)) {
    if (pSearch1->Stdmag < pSearch2->Stdmag) {
      selectSearch1 = 1;
    }
    caseNumber = 1;
  } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
             (pSearch2->flag == REF_TYPE_TYCHO2)) {
    if (pSearch1->Stdmag < pSearch2->Stdmag) {
      selectSearch1 = 1;
    }
    caseNumber = 2;
  } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
             (pSearch2->flag == REF_TYPE_GSC)) {
    selectSearch1 = 1;
    caseNumber = 3;
  } else if ((pSearch1->flag == REF_TYPE_GSC) &&
             (pSearch2->flag == REF_TYPE_TYCHO2)) {
    caseNumber = 4;
  } else if ((pSearch1->flag != REF_TYPE_APASS) &&
             (pSearch2->flag == REF_TYPE_APASS)) {
    caseNumber = 8;
  } else if ((pSearch1->flag == REF_TYPE_APASS) &&
             (pSearch2->flag != REF_TYPE_APASS)) {
    selectSearch1 = 1;
    caseNumber = 12;
  } else if ((pSearch1->flag == REF_TYPE_APASS) &&
             (pSearch2->flag == REF_TYPE_APASS) &&
             (pSearch1->VFlag == 0) &&
             (pSearch2->VFlag == 0)) {
    selectLowRMS = 1;
    caseNumber = 13;
  } else if ((pSearch1->flag == REF_TYPE_APASS) &&
             (pSearch2->flag == REF_TYPE_APASS) &&
             (pSearch1->VFlag == 0) &&
             (pSearch2->VFlag != 0)) {
    selectSearch1 = 1;
    caseNumber = 14;
  } else if ((pSearch1->flag == REF_TYPE_APASS) &&
             (pSearch2->flag == REF_TYPE_APASS) &&
             (pSearch1->VFlag != 0) &&
             (pSearch2->VFlag == 0)) {
    caseNumber = 15;
  } else if ((pSearch1->flag == REF_TYPE_APASS) &&
             (pSearch2->flag == REF_TYPE_APASS) &&
             (pSearch1->VFlag != 0) &&
             (pSearch2->VFlag != 0)) {
    selectLowRMS = 1;
    caseNumber = 16;
  } else {
    caseNumber = 0;
  }
  casetable[caseNumber]++;
  if ((selectSearch1 == 0) &&
      (selectLowRMS != 0)) {
    if (pSearch1->MAGFlag < pSearch2->MAGFlag) {
      selectSearch1 = 1;
    }
  }
  if (selectSearch1 != 0) {
    pSelected = pSearch1;
    pRejected = pSearch2;
  }

  if (mergeHandle != NULL) {
		GetREF(pSelected->REFNumber,selectedREF,1,1);
		GetREF(pRejected->REFNumber,rejectedREF,1,1);
    fprintf(mergeHandle,"%d\t%s\t%f\t%f\t%f\t%f\t%d\t%d\t%d\t%5.1f\t%5.1f\t%s\t%f\t%f\t%f\t%f\t%d\t%d\t%d\t%5.1f\t%5.1f\n",
            caseNumber,
            selectedREF,
            pSelected->ra,
            pSelected->dec,
            pSelected->Stdmag,
            pSelected->color,
            pSelected->class,
            pSelected->VFlag,
            pSelected->MAGFlag,
            pSelected->RaPM,
            pSelected->DecPM,
            rejectedREF,
            pRejected->ra,
            pRejected->dec,
            pRejected->Stdmag,
            pRejected->color,
            pRejected->class,
            pRejected->VFlag,
            pRejected->MAGFlag,
            pRejected->RaPM,
            pRejected->DecPM);
  }
  /* For APASS, we select the entry with the lowest total RMS, currently encoded as an integer in MAGFlag */
  /* Now we have to keep everything in ra ascending order, so shift the remainder of the array */
  if (selectSearch1) {
    /* Throw away the second object */
    for (copyIndex = searchIndex; copyIndex < (sortArraySize-1); copyIndex++) {
      pSearch2 = &pSortMaster[copyIndex];
      pSearch3 = &pSortMaster[copyIndex+1];
      memcpy(pSearch2,pSearch3,sizeof(GSCAPASSIMAGE));
    }
    if (curIndex > searchIndex) {
      curIndex--;  /* First object has moved */
    }
  
  } else {
    /* Throw away the first object */
    for (copyIndex = curIndex; copyIndex < (sortArraySize-1); copyIndex++) {
      pSearch2 = &pSortMaster[copyIndex];
      pSearch3 = &pSortMaster[copyIndex+1];
      memcpy(pSearch2,pSearch3,sizeof(GSCAPASSIMAGE));
    }

  }

  *pCurIndex = curIndex;
  return;

}


void SaveDecBin(File outputHandle,
                File indexHandle,
                PGSCAPASSIMAGE pSortMaster,
                int sortArraySize,
                int oldDecBin,
                double radiusArcsec,
                int catalogNumber,
                int placeHolder,
                int griPresent,
                int *savedDecBin,
                int *maxWriteCount,
                int *duplicateCount)
{
  int dec_bin;
  off_t curOffset = 0;
  int curSortIndex = 0;
  PBININDEX pBinIndex = pGscBin64->pBinMasterIndex;
  int binNumber;
  int numBins;
  int endBinNumber;
  int writeItems;
  int subBin;
  int writeCount;
  int totalWriteCount = 0;
  double startRa2;
  double endRa2;
  double startDec;
  double endDec;
  STARINDEX starIndex;
  PSTARINDEX pStarIndex = &starIndex;
  PGSCAPASSIMAGE pMaster = pSortMaster;

  GSCIMAGE outMaster;
  PGSCIMAGE pOutMaster = &outMaster;

  double declination;
  int beginIndex = 0;
  int curIndex = 0;
  int searchIndex;
  int copyIndex;
  PGSCAPASSIMAGE pSearch1;
  PGSCAPASSIMAGE pSearch2;
  PGSCAPASSIMAGE pSearch3;
  double maxRa;
  double startRa;
  double endRa;
  double lowDec;
  double highDec;
  double dist;
  double factor;
  double dist2;
  int restartFlag;
  double maxDec;
  int magBinNumber;
  int colorType;
	char search1REF[MAX_REF];
	char search2REF[MAX_REF];

  if (outputHandle != NULL) {
    curOffset = Tell(outputHandle);
  }
  if (sortArraySize > 0) {
    /* Sort the array numerically in the order of increasing right ascension */
    qsort((void*)pSortMaster,sortArraySize,sizeof(GSCAPASSIMAGE),ImageCompare);
  }
  if (radiusArcsec > 0.0) {
    /* Now go through this bin looking for duplicates */
    maxDec = radiusArcsec/3600.;
    pBinIndex =  &pGscBin64->pBinMasterIndex[oldDecBin];
    declination = pBinIndex->declination + ((pGscBin64->bin_size)/2.0);
    factor = cos(DEGREES_TO_RAD * declination);
    if (fabs(declination) > 90.0 - (5*pGscBin64->bin_size)) {
      maxRa = 360.0;
    } else {
      maxRa = maxDec/factor;
    }
    while (curIndex < sortArraySize) {
#if 0
      if ((oldDecBin == 90) && (curIndex == 17)) {
        printf("At oldDecBin %d and curIndex %d\n",oldDecBin,curIndex);
      }
#endif
      restartFlag = 0;
      pSearch1 = &pSortMaster[curIndex];
      startRa = pSearch1->ra - maxRa;
      endRa = pSearch1->ra + maxRa;
      lowDec = pSearch1->dec - maxDec;
      highDec = pSearch1->dec + maxDec;
      /* Search #1 - no wrap */
      searchIndex = beginIndex;
      while (searchIndex < sortArraySize) {
        if (searchIndex == curIndex) {
          searchIndex++;
        } else {
          pSearch2 = &pSortMaster[searchIndex];
          if (pSearch2->ra < startRa) {
            beginIndex++;
            searchIndex++;
          } else {
            if (pSearch2->ra > endRa) {
              break;
            } else {
              if ((pSearch2->dec < lowDec) ||
                  (pSearch2->dec > highDec)) {
                searchIndex++;
              } else {
                factor = cos(DEGREES_TO_RAD * ((pSearch1->dec+pSearch2->dec)/2.0));
                dist = sqrt(sqr(factor * (pSearch1->ra - pSearch2->ra)) + sqr(pSearch1->dec-pSearch2->dec));
                if (dist > radiusArcsec/3600.) {
                  searchIndex++;
                } else {
                  /* This is truly a duplicate */
                  dist2 = wcsdist(pSearch1->ra,pSearch1->dec,pSearch2->ra,pSearch2->dec);
                  (*duplicateCount)++;
#if 0
                  printf("ERROR: duplicate (1) at Stdmag %.2f %.2f ra %f %f and dec %f %f dist %f %f arcsec  %d %d %d\n",pSearch1->Stdmag,pSearch2->Stdmag,pSearch1->ra,pSearch2->ra,pSearch1->dec,pSearch2->dec,dist*3600.0,3600.0*dist2,oldDecBin,curIndex,searchIndex);
#endif
                  if (placeHolder) {
                    RejectPlaceHolderDuplicate(pSearch1,pSearch2,pSortMaster,sortArraySize,&curIndex,searchIndex);
                  } else if (catalogNumber == CATALOG_APASS) {
                    /* We go by the following truth table to select pSearch1 or pSearch2 */
                    /*      Catalog    good RMS            */
                    /*     S1   S2    S1   S2              */
                    /*  1   T    T    OK   OK    Lowest RMS*/
                    /*  2   T    T    OK   V        S1     */
                    /*  3   T    T    V    OK       S2     */
                    /*  4   T    T    V    V     Lowest RMS*/
                    /*  5   T    A    OK   OK       S2       -> PRINT MERGE TABLE */
                    /*  6   T    A    OK   V        S1     */
                    /*  7   T    A    V    OK       S2     */
                    /*  8   T    A    V    V        S2     */
                    /*  9   A    T    OK   OK       S1       -> PRINT MERGE TABLE */
                    /* 10   A    T    OK   V        S1     */
                    /* 11   A    T    V    OK       S2     */
                    /* 12   A    T    V    V        S1     */
                    /* 13   A    A    OK   OK    Lowest RMS*/
                    /* 14   A    A    OK   V        S1     */
                    /* 15   A    A    V    OK       S2     */
                    /* 16   A    A    V    V     Lowest RMS*/

                    int selectSearch1 = 0;
                    int selectLowRMS  = 0;
                    if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                        (pSearch2->flag == REF_TYPE_TYCHO2) &&
                        (pSearch1->VFlag == 0) &&
                        (pSearch2->VFlag == 0)) {
                      selectLowRMS = 1;
                      casetable[1]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag != 0)) {
                      selectLowRMS = 1;
                      casetable[4]++;
                    }  else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                                (pSearch2->flag != REF_TYPE_TYCHO2) &&
                                (pSearch1->VFlag == 0) &&
                                (pSearch2->VFlag == 0)) {
                      selectLowRMS = 1;
                      casetable[13]++;
                    }   else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                                 (pSearch2->flag != REF_TYPE_TYCHO2) &&
                                 (pSearch1->VFlag != 0) &&
                                 (pSearch2->VFlag != 0)) {
                      selectLowRMS = 1;
                      casetable[16]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag == 0) &&
                               (pSearch2->VFlag != 0)) {
                      selectSearch1 = 1;
                      casetable[2]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag != REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag == 0) &&
                               (pSearch2->VFlag != 0)) {
                      selectSearch1 = 1;
                      casetable[6]++;
                    } else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag == 0) &&
                               (pSearch2->VFlag == 0)) {
                      selectSearch1 = 1;
                      casetable[9]++;
                    } else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag == 0) &&
                               (pSearch2->VFlag != 0)) {
                      selectSearch1 = 1;
                      casetable[10]++;
                    } else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag != 0)) {
                      selectSearch1 = 1;
                      casetable[12]++;
                    } else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                               (pSearch2->flag != REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag == 0) &&
                               (pSearch2->VFlag != 0)) {
                      selectSearch1 = 1;
                      casetable[14]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag == 0)) {
                      casetable[3]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag != REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag == 0) &&
                               (pSearch2->VFlag == 0)) {
                      if (mergeHandle != NULL) {
												GetREF(pSearch1->REFNumber,search1REF,1,1);
												GetREF(pSearch2->REFNumber,search2REF,1,1);

                        fprintf(mergeHandle,"%s\t%f\t%f\t%f\t%f\t%d\t%d\t%d\t%5.1f\t%5.1f\t%s\t%f\t%f\t%f\t%f\t%d\t%d\t%d\t%5.1f\t%5.1f\n",
                                search1REF,
                                pSearch1->ra,
                                pSearch1->dec,
                                pSearch1->Stdmag,
                                pSearch1->color,
                                pSearch1->class,
                                pSearch1->VFlag,
                                pSearch1->MAGFlag,
                                pSearch1->RaPM,
                                pSearch1->DecPM,
                                search2REF,
                                pSearch2->ra,
                                pSearch2->dec,
                                pSearch2->Stdmag,
                                pSearch2->color,
                                pSearch2->class,
                                pSearch2->VFlag,
                                pSearch2->MAGFlag,
                                pSearch2->RaPM,
                                pSearch2->DecPM);

                      }
                      casetable[5]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag != REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag == 0)) {
                      casetable[7]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag != REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag != 0)) {
                      casetable[8]++;
                    } else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag == 0)) {
                      casetable[11]++;
                    } else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                               (pSearch2->flag != REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag == 0)) {
                      casetable[15]++;
                    } else {
                      casetable[0]++;
                    }




                    if ((selectSearch1 == 0) &&
                        (selectLowRMS != 0)) {
                      if (pSearch1->MAGFlag < pSearch2->MAGFlag) {
                        selectSearch1 = 1;
                      }
                    }

                    /* For APASS, we select the entry with the lowest total RMS, currently encoded as an integer in MAGFlag */
                    /* Now we have to keep everything in ra ascending order, so shift the remainder of the array */
                    if (selectSearch1) {
                      /* Throw away the second object */
                      for (copyIndex = searchIndex; copyIndex < (sortArraySize-1); copyIndex++) {
                        pSearch2 = &pSortMaster[copyIndex];
                        pSearch3 = &pSortMaster[copyIndex+1];
                        memcpy(pSearch2,pSearch3,sizeof(GSCAPASSIMAGE));
                      }
                      if (curIndex > searchIndex) {
                        curIndex--;  /* First object has moved */
                      }
  
                    } else {
                      /* Throw away the first object */
                      for (copyIndex = curIndex; copyIndex < (sortArraySize-1); copyIndex++) {
                        pSearch2 = &pSortMaster[copyIndex];
                        pSearch3 = &pSortMaster[copyIndex+1];
                        memcpy(pSearch2,pSearch3,sizeof(GSCAPASSIMAGE));
                      }

                    }
                  }
                  sortArraySize--;
                  restartFlag = 1;
                  break;
                }
              }
            }
          }
        }
      }
      /* Search 2 is necessary if we wrap around */
      if ((restartFlag == 0) && ((startRa < 0.0) || (endRa >= 360.0))) {
        searchIndex = sortArraySize - 1;
        while (searchIndex >= 0) {
          if (searchIndex == curIndex) {
            searchIndex--;
          } else {
            pSearch2 = &pSortMaster[searchIndex];
            dist = 360.0 - fabs(pSearch2->ra-startRa);
            if (dist > maxRa) {
              break;
            } else {
              if ((pSearch2->dec < lowDec) ||
                  (pSearch2->dec > highDec)) {
                searchIndex--;
              } else {
                factor = cos(DEGREES_TO_RAD * ((pSearch1->dec+pSearch2->dec)/2.0));
                dist = sqrt(sqr(factor * (360.0 - fabs(pSearch1->ra - pSearch2->ra))) + sqr(pSearch1->dec-pSearch2->dec));
                if (dist > radiusArcsec/3600.) {
                  searchIndex--;
                } else {
                  /* This is truly a duplicate */
                  dist2 = wcsdist(pSearch1->ra,pSearch1->dec,pSearch2->ra,pSearch2->dec);
                  (*duplicateCount)++;
#if 1
                  printf("ERROR: duplicate (2) at ra %f %f and dec %f %f dist %f %f arcsec  %d %d %d\n",pSearch1->ra,pSearch2->ra,pSearch1->dec,pSearch2->dec,dist*3600.0,3600.0*dist2,oldDecBin,curIndex,searchIndex);
#endif
                  if (placeHolder) {
                    RejectPlaceHolderDuplicate(pSearch1,pSearch2,pSortMaster,sortArraySize,&curIndex,searchIndex);
                  } else if (catalogNumber == CATALOG_APASS) {
                    printf("ERROR: wraparound search is untested and not in sync with tested code\n");
                    exit(-1);
                    /* We go by the following truth table to select pSearch1 or pSearch2 */
                    /*      Catalog    good RMS            */
                    /*     S1   S2    S1   S2              */
                    /*      T    T    OK   OK    Lowest RMS*/
                    /*      T    T    OK   V        S1     */
                    /*      T    T    V    OK       S2     */
                    /*      T    T    V    V     Lowest RMS*/
                    /*      T    A    OK   OK       S2     */
                    /*      T    A    OK   V        S1     */
                    /*      T    A    V    OK       S2     */
                    /*      T    A    V    V        S2     */
                    /*      A    T    OK   OK       S1     */
                    /*      A    T    OK   V        S1     */
                    /*      A    T    V    OK       S2     */
                    /*      A    T    V    V        S1     */
                    /*      A    A    OK   OK    Lowest RMS*/
                    /*      A    A    OK   V        S1     */
                    /*      A    A    V    OK       S2     */
                    /*      A    A    V    V     Lowest RMS*/

                    int selectSearch1 = 0;
                    int selectLowRMS  = 0;
                    if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                        (pSearch2->flag == REF_TYPE_TYCHO2) &&
                        (pSearch1->VFlag == 0) &&
                        (pSearch2->VFlag == 0)) {
                      selectLowRMS = 1;
                      casetable[1]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag != 0)) {
                      selectLowRMS = 1;
                      casetable[4]++;
                    }  else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                                (pSearch2->flag != REF_TYPE_TYCHO2) &&
                                (pSearch1->VFlag == 0) &&
                                (pSearch2->VFlag == 0)) {
                      selectLowRMS = 1;
                      casetable[13]++;
                    }   else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                                 (pSearch2->flag != REF_TYPE_TYCHO2) &&
                                 (pSearch1->VFlag != 0) &&
                                 (pSearch2->VFlag != 0)) {
                      selectLowRMS = 1;
                      casetable[16]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag == 0) &&
                               (pSearch2->VFlag != 0)) {
                      selectSearch1 = 1;
                      casetable[2]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag != REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag == 0) &&
                               (pSearch2->VFlag != 0)) {
                      selectSearch1 = 1;
                      casetable[6]++;
                    } else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag == 0) &&
                               (pSearch2->VFlag == 0)) {
                      selectSearch1 = 1;
                      casetable[9]++;
                    } else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag == 0) &&
                               (pSearch2->VFlag != 0)) {
                      selectSearch1 = 1;
                      casetable[10]++;
                    } else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag != 0)) {
                      selectSearch1 = 1;
                      casetable[12]++;
                    } else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                               (pSearch2->flag != REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag == 0) &&
                               (pSearch2->VFlag != 0)) {
                      selectSearch1 = 1;
                      casetable[14]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag == 0)) {
                      casetable[3]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag != REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag == 0) &&
                               (pSearch2->VFlag == 0)) {

                      if (mergeHandle != NULL) {
												GetREF(pSearch1->REFNumber,search1REF,1,1);
												GetREF(pSearch2->REFNumber,search2REF,1,1);

                        fprintf(mergeHandle,"%s\t%f\t%f\t%f\t%f\t%d\t%d\t%d\t%5.1f\t%5.1f\t%s\t%f\t%f\t%f\t%f\t%d\t%d\t%d\t%5.1f\t%5.1f\n",
                                search1REF,
                                pSearch1->ra,
                                pSearch1->dec,
                                pSearch1->Stdmag,
                                pSearch1->color,
                                pSearch1->class,
                                pSearch1->VFlag,
                                pSearch1->MAGFlag,
                                pSearch1->RaPM,
                                pSearch1->DecPM,
                                search2REF,
                                pSearch2->ra,
                                pSearch2->dec,
                                pSearch2->Stdmag,
                                pSearch2->color,
                                pSearch2->class,
                                pSearch2->VFlag,
                                pSearch2->MAGFlag,
                                pSearch2->RaPM,
                                pSearch2->DecPM);

                      }
                      casetable[5]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag != REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag == 0)) {
                      casetable[7]++;
                    } else if ((pSearch1->flag == REF_TYPE_TYCHO2) &&
                               (pSearch2->flag != REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag != 0)) {
                      casetable[8]++;
                    } else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                               (pSearch2->flag == REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag == 0)) {
                      casetable[11]++;
                    } else if ((pSearch1->flag != REF_TYPE_TYCHO2) &&
                               (pSearch2->flag != REF_TYPE_TYCHO2) &&
                               (pSearch1->VFlag != 0) &&
                               (pSearch2->VFlag == 0)) {
                      casetable[15]++;
                    } else {
                      casetable[0]++;
                    }
                    if ((selectSearch1 == 0) &&
                        (selectLowRMS != 0)) {
                      if (pSearch1->MAGFlag < pSearch2->MAGFlag) {
                        selectSearch1 = 1;
                      }
                    }

                    /* For APASS, we select the entry with the lowest total RMS, currently encoded as an integer in MAGFlag */
                    /* Now we have to keep everything in ra ascending order, so shift the remainder of the array */
                    if (selectSearch1) {
                      /* Throw away the second object */
                      for (copyIndex = searchIndex; copyIndex < (sortArraySize-1); copyIndex++) {
                        pSearch2 = &pSortMaster[copyIndex];
                        pSearch3 = &pSortMaster[copyIndex+1];
                        memcpy(pSearch2,pSearch3,sizeof(GSCAPASSIMAGE));
                      }
                      if (curIndex > searchIndex) {
                        curIndex--;  /* First object has moved */
                      }
  
                    } else {
                      /* Throw away the first object */
                      for (copyIndex = curIndex; copyIndex < (sortArraySize-1); copyIndex++) {
                        pSearch2 = &pSortMaster[copyIndex];
                        pSearch3 = &pSortMaster[copyIndex+1];
                        memcpy(pSearch2,pSearch3,sizeof(GSCAPASSIMAGE));
                      }

                    }
                  }
                  restartFlag = 1;
                  sortArraySize--;
                  break;
                }
              }
            }
          }
        }
      }
      if (restartFlag == 0) {
        curIndex++;
      }
    }
    
    

  }


  for (dec_bin = (*savedDecBin)+1; dec_bin <= oldDecBin; dec_bin++) {
    if (dec_bin < 0) {
      continue;
    }
    if ((dec_bin == oldDecBin) &&
        (totalWriteCount != 0)) {
      printf("ERROR: totalWriteCount nonzero for bin preceeding %d\n",oldDecBin);
      exit(-1);
    }
    pBinIndex =  &pGscBin64->pBinMasterIndex[dec_bin];
    startDec = pBinIndex->declination;
    endDec = startDec + pGscBin64->bin_size;

    numBins = pBinIndex->numBins;
    endBinNumber = pBinIndex->startBin + numBins -1;
    for (binNumber = pBinIndex->startBin; binNumber <= endBinNumber; binNumber++) {

      subBin = binNumber - pBinIndex->startBin;
      startRa2 = (360.0*subBin)/numBins;
      endRa2 = (360.0*(subBin+1))/numBins;
      writeCount = 0;
      while ((curSortIndex < sortArraySize) && 
             (oldDecBin == dec_bin) &&
             (pMaster->ra >= startRa2) && 
             (pMaster->ra < endRa2)) {
        writeCount++;
        if (outputHandle != NULL) {
          if (catalogNumber == CATALOG_APASS) {
            /* Done with MAGFlag for APASS and Tycho2, which is really an encoded rms value */
            if (pMaster->flag == REF_TYPE_TYCHO2) {
              pMaster->MAGFlag =  COLOR_TYCHO;
            } else if (pMaster->flag == REF_TYPE_APASS) {
              pMaster->MAGFlag = 0;
            }
            if ((placeHolder != 0) && (pMaster->flag != REF_TYPE_APASS)) {
              /* All non-APASS stars are rejected by setting the variable flag */
              pMaster->VFlag = 1;
            }
          }

					pMaster->flag = 0; /* Done with the flag bit used as refType */
          if (griPresent != 0) {
            writeItems = Write(outputHandle,pMaster,sizeof(GSCAPASSIMAGE),1);
            if (writeItems != 1) {
              printf("ERROR writing the output file\n");
              exit(-1);
            }
          } else {
            memset(pOutMaster,0,sizeof(pOutMaster));
            pOutMaster->REFNumber = pMaster->REFNumber;
            pOutMaster->ra = pMaster->ra;
            pOutMaster->dec = pMaster->dec;
            pOutMaster->Stdmag = pMaster->Stdmag;
            pOutMaster->color = pMaster->color;
            pOutMaster->RaPM = pMaster->RaPM;
            pOutMaster->DecPM = pMaster->DecPM;
            pOutMaster->RaSigmaPM = pMaster->RaSigmaPM;
            pOutMaster->DecSigmaPM = pMaster->DecSigmaPM;
            pOutMaster->class = pMaster->class;
            pOutMaster->VFlag = pMaster->VFlag;
            pOutMaster->MAGFlag = pMaster->MAGFlag;
            pOutMaster->flag = pMaster->flag;
            writeItems = Write(outputHandle,pOutMaster,sizeof(GSCIMAGE),1);
            if (writeItems != 1) {
              printf("ERROR writing the output file\n");
              exit(-1);
            }
            
          }

#if 1
          if (pMaster->VFlag == 0) {
            if (pMaster->MAGFlag == COLOR_JPGMAG_FPGMAG) {
              colorType = COLORINDEX_GSC;
            } else if (pMaster->MAGFlag == COLOR_TYCHO) {
              colorType = COLORINDEX_TYCHO;
            } else {
              colorType = COLORINDEX_NEITHER;
            }
            allcount[colorType]++;
            magBinNumber = (MAGBASE - pMaster->Stdmag)/MAGINC;
            if (magBinNumber < 0) {
              magBinNumber = 0;
            }
            if (magBinNumber > (MAGBINS-2)) {
              magBinNumber = MAGBINS-2;
            }
            ++magcount[colorType][magBinNumber];
            avecolor[colorType][magBinNumber] += pMaster->color;
          }
#endif
        }
        if ((pMaster->dec < startDec) || (pMaster->dec >= endDec)) {
          printf("ERROR: incorrect declination bin\n");
          exit(-1);
        }
        pMaster++;
        curSortIndex++;
        if (curSortIndex > sortArraySize) {
          printf("ERROR: Sort array size exceeded\n");
        }
      }
      pStarIndex->offset = curOffset;
      pStarIndex->binNumber = binNumber;
      pStarIndex->numStars = writeCount;
      totalWriteCount += writeCount;
      if (indexHandle != NULL) {
        writeItems = Write(indexHandle,pStarIndex,sizeof(STARINDEX),1);
        if (writeItems != 1) {
          printf("ERROR writing the index file\n");
          exit(-1);
        }
      }
      if (writeCount > 0) {
        if (outputHandle != NULL) {
          curOffset = Tell(outputHandle);
        }
        if (writeCount > *maxWriteCount) {
          *maxWriteCount = writeCount;
        }
      }
    }
  }
  *savedDecBin = oldDecBin;
  if (totalWriteCount != sortArraySize) {
    printf("ERROR in sort array size for oldDecBin %d\n",oldDecBin);
    printf("last ra %f dec %f REFNumber %lld\n",pMaster->ra,pMaster->dec,pMaster->REFNumber);
    exit(-1);
  }
  if (curSortIndex != sortArraySize) {
    printf("ERROR in sort array index for oldDecBin %d\n",oldDecBin);
    exit(-1);
  }
}

int main(int argc,char *argv[])
{
  char *argstr;
	char rootname[MAX_MASTER_NAME];
  char outputname[MAX_MASTER_NAME];
  File outputHandle = NULL;
  char indexname[MAX_MASTER_NAME];
  File indexHandle = NULL;
  char zeromagname[MAX_MASTER_NAME];
  FILE *zeromagHandle = NULL;
  char gmtBaseName[] = "/dasch/scanner/linux/gmt/";
  char gmtFileName[MAX_MASTER_NAME];
  FILE *gmtHandle;
  char mergeFileName[MAX_MASTER_NAME];

  int zeromagCount = 0;
  int errorFlag = 0;
  time_t startTime;
  time_t curTime;
  int linecounter = 0;
  int index;
  char *charPtr;
  char cmdchar;
  int verbose = 0;
  int placeHolder = 0;
  char *dotPtr = NULL;
	char *slashPtr;
  int compareResult;
  int binNumber;
  int binNumber01;
  int oldBinNumber = -1;
  int dec_bin;
  int dec_bin2;
  int dec_bin01;
  int oldDecBin = 0;
  int savedDecBin = -2;
  int ra_bin;
  int ra_bin01;
  int *decBinCounts = NULL;
  int maxDecBin = 0;
  double maxRaError = 0;
  double maxDecError = 0;
  int maxWriteCount = 0;
  int totalBinCount = 0;

  File master_handle = NULL;
  char master_name[MAX_MASTER_NAME];
  TableHead master_header = NULL;
  int master_nrecs = 0;
  int master_index;
  GSCAPASSIMAGE master_record;
  PGSCAPASSIMAGE pMaster = &master_record;
  GSCAPASSIMAGE old_master_record;
  PGSCAPASSIMAGE pOldMaster = &old_master_record;
  TblDescriptor master_descriptor = NULL;
  TableRow master_row = NULL;
  PGSCAPASSIMAGE pSortMaster = NULL;
  int sortArrayAlloc = 0;
  int sortArraySize = 0;
  int nvals;


  double tmpRaPM;
  double tmpDecPM;
  double tmpPM;
  double maxRaPM = 0;
  double maxDecPM = 0;
  double maxPM = 0;
  int countPM = 0;

  int skipOutput = 0;
  int magBinNumber;
  int colorType = 0;
  int *gridarray;
  double radiusArcsec = -1.0;
  int catalogNumber = CATALOG_GSC232;
  int duplicateCount = 0;
	int gotREFNumber = 0;
	int gotRaSigmaPM = 0;
	int gotDecSigmaPM = 0;
	int columnIndex;
	int sigmaPMPresent = 0;
  int gotGmag = 0;
  int gotRmag = 0;
  int gotImag = 0;
  int gotVmagerr = 0;
  int gotBmagerr = 0;
  int gotGmagerr = 0;
  int gotRmagerr = 0;
  int gotImagerr = 0;
  int griPresent = 0;
  int ra360count = 0;
  int ranegcount = 0;

  decBinCounts = (int *)calloc(pGscBin64->dec_bins,sizeof(int));

  gridarray = (int *)calloc(pGscBin01->total_gsc_bins,sizeof(int));

  /* Loop through the arguments */
  master_name[0] = 0;
  outputname[0] = 0;
  indexname[0] = 0;
  zeromagname[0] = 0;
	rootname[0] = 0;


  memset(magcount,0,sizeof(magcount));
  memset(avecolor,0,sizeof(avecolor));
  memset(magnorm,0,sizeof(magnorm));
  memset(casetable,0,sizeof(casetable));
  memset(maxcount,0,sizeof(maxcount));
  memset(allcount,0,sizeof(allcount));
  int maxREFLength = 0;
  char maxREF[2*MAX_REF]; 
	char masterREF[2*MAX_REF];
  char oldMasterREF[MAX_REF];

  maxREF[0] = 0;
  for (argv++; --argc > 0; argv++) {
    argstr = *argv;
    /* Decode arguments */
    if (argstr[0] != '-') {
      /* This must be the list of plates */
      if (strlen(master_name) > 0) {
        errorFlag = 1;
        printf("ERROR: list %s is being overwritten by %s\n",master_name,argstr);
      } else {
        strncpy(master_name,argstr,MAX_MASTER_NAME-1);
      }
    } else {
      while ((cmdchar = *++argstr) != 0) {
        switch(cmdchar) {
        case 'v':
        case 'V':
          verbose = 1;
          break;
        case 'p':
        case 'P':
          placeHolder = 1;
          break;
        case 'q': /* Catalog and file name */
        case 'Q':
          argc--;
          if (argc < 1) {
            printf("ERROR: Insufficient arguments for -%c\n",cmdchar);
            errorFlag = 1;
          } else {
            catalogNumber = GetCatalogNumber(*++argv);
            
            if (catalogNumber < 0) {
              printf("ERROR: Illegal catalog name %s\n",*argv);
              errorFlag = 1;
            }
          }
          break;

        case 'o': /* Output file root */
        case 'O':
          argc--;
          if (argc < 1) {
            printf("ERROR: Insufficient arguments for -%c\n",cmdchar);
            errorFlag = 1;
          } else {
						++argv;
						if (strlen(*argv) > (MAX_MASTER_NAME-1)) {
							printf("ERROR: output name is too large\n");
							exit(-1);
						}
						strcpy(rootname,*argv);
					}
					break;


        case 's':
        case 'S':
          skipOutput = 1;
          break;

        case 'r': /* match radius in arcsec */
        case 'R':
          argc--;
          if (argc < 1) {
            printf("ERROR: Insufficient arguments for -%c\n",cmdchar);
            errorFlag = 1;
          } else {
            nvals = sscanf(*++argv,"%lf",&radiusArcsec);
            if (nvals != 1) {
              printf("ERROR: Unable to decode right margin %s\n",*argv);
              errorFlag = 1;
            }
          }
          break;



        default:
          printf("* illegal command -%c-",cmdchar);
          errorFlag = 1;
          break;
        }
        
      }
    }
  }
  if ((placeHolder != 0) && 
      (catalogNumber != CATALOG_APASS)) {
    printf("ERROR: Placeholder operation applies only for the APASS catalog\n");
    errorFlag = 1;
  }


  /* Attempt to open the list */
  if (master_name[0] == 0) {
    printf("Input file name not specified\n");
    errorFlag = 1;
  } else {

    master_handle = Open(master_name,"r");
    if (master_handle == NULL) {
      printf("Could not open file %s\n",master_name);
      errorFlag = 1;
    } 
  }

  strcpy(outputname,master_name);
	if (rootname[0] != 0) {
		slashPtr = strrchr(outputname,'/');
		if (slashPtr == NULL) {
			slashPtr = outputname;
		} else {
			slashPtr++;
		}
		strcpy(slashPtr,rootname);
	} else {
		dotPtr = strstr(outputname,".");
		if (dotPtr != NULL) {
			*dotPtr = 0;
		}
	}
  strcat(outputname,".dat");


  strcpy(gmtFileName,gmtBaseName);
  charPtr = strrchr(outputname,'/');
  if (charPtr == NULL) {
    printf("ERROR: Could not find / in %s\n",outputname);
  } else {
    charPtr++;
    strcat(gmtFileName,charPtr);
    charPtr = strrchr(gmtFileName,'.');
    if (charPtr == NULL) {
      printf("ERROR: Could not find dot in %s\n",gmtFileName);
    } else {
      *charPtr = 0;
      strcat(gmtFileName,".txt");
      gmtHandle = fopen(gmtFileName,"wt");
      if (gmtHandle == NULL) {
        printf("ERROR: Failed to open %s\n",gmtFileName);
      }
    }
  }

  if (catalogNumber == CATALOG_APASS) {
    strcpy(mergeFileName,outputname);
    charPtr = strrchr(mergeFileName,'/');
    if (charPtr != NULL) {
      charPtr++;
      *charPtr = 0;
    }
    strcat(mergeFileName,"apass_merge.db");
    mergeHandle = fopen(mergeFileName,"wt");
    if (mergeHandle == NULL) {
      printf("ERROR: failed to open %s\n",mergeFileName);
    } else {
      if (placeHolder) {
        fprintf(mergeHandle,"sequence\tGREF\tGra\tGdec\tGStdmag\tGcolor\tGclass\tGVFlag\tGMAGFlag\tGRaPM\tGDecPM\tKREF\tKra\tKdec\tKStdmag\tKcolor\tKclass\tKVFlag\tKMAGFlag\tKRaPM\tKDecPM\n");
        fprintf(mergeHandle,"--------\t----\t---\t----\t-------\t------\t------\t------\t--------\t-----\t------\t----\t---\t----\t-------\t------\t------\t------\t--------\t-----\t------\n");
      } else {
        fprintf(mergeHandle,"GREF\tGra\tGdec\tGStdmag\tGcolor\tGclass\tGVFlag\tGMAGFlag\tGRaPM\tGDecPM\tKREF\tKra\tKdec\tKStdmag\tKcolor\tKclass\tKVFlag\tKMAGFlag\tKRaPM\tKDecPM\n");
        fprintf(mergeHandle,"----\t---\t----\t-------\t------\t------\t------\t--------\t-----\t------\t----\t---\t----\t-------\t------\t------\t------\t--------\t-----\t------\n");
      }
    }
  }


  strcpy(indexname,outputname);
  dotPtr = strstr(indexname,".");
  if (dotPtr != NULL) {
    *dotPtr = 0;
  }
  strcat(indexname,".idx");

  strcpy(zeromagname,outputname);
  dotPtr = strstr(zeromagname,".");
  if (dotPtr != NULL) {
    *dotPtr = 0;
  }
  strcat(zeromagname,"_zero.db");




  if (errorFlag) {
    printf("Usage: formatgsc <master_name> [-v][-s][-r <arcsec>}[-q <catalog>][-o <outputprefix>]\n");
    printf("       where -v is the verbose flag\n");
    printf("       where -r <arcsec> eliminates duplicates within the given radius\n");
    printf("       where -s provides statistics only and skips writing output files\n");
    printf("       where -q <catalog> (only kepler and apass are currently recognized)\n");
    printf("       where -o <outputprefix> (output name prefix)\n");

    return(-1);
  }

  printf("formatgsc of %s %s match radius %f arcsec placeHolder %d\n Input Filename %s\n Output Filename %s\n Index Filename %s\n Zero Magnitude File %s\n",
         __DATE__,__TIME__,radiusArcsec,placeHolder,master_name,outputname,indexname,zeromagname);
  printf("Size of BININDEX is %d.  Size of STARINDEX is %d. Size of GSCIMAGE is %d size of GSCIMAGEC is %d size of GSCAPASSIMAGE is %d \n",sizeof(BININDEX),sizeof(STARINDEX),sizeof(GSCIMAGE),sizeof(GSCIMAGEC),sizeof(GSCAPASSIMAGE));
 

  time(&startTime);
  
  if (skipOutput == 0) {
    outputHandle = Open(outputname,"w");
    if (outputHandle == NULL) {
      printf("Could not open file %s\n",outputname);
      exit(-1);
    } 
    indexHandle = Open(indexname,"w");
    if (indexHandle == NULL) {
      printf("Could not open file %s\n",indexname);
      exit(-1);
    } 
    zeromagHandle = fopen(zeromagname,"wb");
    if (zeromagHandle == NULL) {
      printf("Could not open file %s\n",zeromagname);
      exit(-1);
    } 
    fprintf(zeromagHandle,"REF\tra\tdec\tStdmag\tcolor\tclass\tVFlag\tMAGFlag\tRaPM\tDecPM\tRaSigmaPM\tDecSigmaPM\n");
    fprintf(zeromagHandle,"---\t--\t---\t------\t-----\t-----\t-----\t-------\t----\t-----\t---------\t----------\n");
  }

  /* Now read in the master file */

  master_header = table_header(master_handle,TABLE_PARSE);
  if (master_header == NULL) {
    printf("ERROR: Failed to read header for %s\n",master_name);
    return(-1);
  }
	/* At this point, check the file to see if the REFNumber, RaSigmaPM, and DecSigmaPM fields are present */
	gotREFNumber = 0;
	gotRaSigmaPM = 0;
	gotDecSigmaPM = 0;
	for (columnIndex = 1; columnIndex <= master_header->header->ncol; columnIndex++) {
		if (strcmp(master_header->header->column[columnIndex],"REFNumber") == 0) {
			gotREFNumber = 1;
		}
		if (strcmp(master_header->header->column[columnIndex],"RaSigmaPM") == 0) {
			gotRaSigmaPM = 1;
		}
		if (strcmp(master_header->header->column[columnIndex],"DecSigmaPM") == 0) {
			gotDecSigmaPM = 1;
		}

		if (strcmp(master_header->header->column[columnIndex],"gmag") == 0) {
			gotGmag = 1;
		}
		if (strcmp(master_header->header->column[columnIndex],"rmag") == 0) {
			gotRmag = 1;
		}
		if (strcmp(master_header->header->column[columnIndex],"imag") == 0) {
			gotImag = 1;
		}
		if (strcmp(master_header->header->column[columnIndex],"vmagerr") == 0) {
			gotVmagerr = 1;
		}
		if (strcmp(master_header->header->column[columnIndex],"bmagerr") == 0) {
			gotBmagerr = 1;
		}
		if (strcmp(master_header->header->column[columnIndex],"gmagerr") == 0) {
			gotGmagerr = 1;
		}
		if (strcmp(master_header->header->column[columnIndex],"rmagerr") == 0) {
			gotRmagerr = 1;
		}
		if (strcmp(master_header->header->column[columnIndex],"imagerr") == 0) {
			gotImagerr = 1;
		}


	}
	if ((gotREFNumber == 0) && (sigmaPMPresent != 0)) {
		printf("ERROR: no REFNumber column in %s\n",master_name);
	}
	if ((gotRaSigmaPM == 0) && (gotDecSigmaPM == 0)) {
		sigmaPMPresent = 0;
	} else if ((gotRaSigmaPM == 1) && (gotDecSigmaPM == 1)) {
		sigmaPMPresent = 1;
	} else {
		printf("ERROR: only one of RaSigmaPM %d or DecSigmaPM %d is present in %s\n",
					 gotRaSigmaPM,
					 gotDecSigmaPM,
					 master_name);
		exit(-1);
	}
  if ((gotGmag == 1) &&
      (gotRmag == 1) &&
      (gotImag == 1) &&
      (gotVmagerr == 1) &&
      (gotBmagerr == 1) &&
      (gotGmagerr == 1) &&
      (gotRmagerr == 1) &&
      (gotImagerr == 1)) {
    griPresent = 1;
  }
      

	if (gotREFNumber == 0) {
    if (catalogNumber == CATALOG_APASS) {
      master_descriptor = table_create_descrip(&master_nrecs,
                                               TblBuf,"REF"      ,TblOff(PGSCIMAGEC,REFNumber),2*MAX_REF,
                                               TblDbl,"ra"       ,TblOff(PGSCIMAGEC,ra),
                                               TblDbl,"dec"      ,TblOff(PGSCIMAGEC,dec),
                                               TblFlt,"Stdmag"   ,TblOff(PGSCIMAGEC,Stdmag),
                                               TblFlt,"color"    ,TblOff(PGSCIMAGEC,color),
                                               TblFlt,"RaPM"     ,TblOff(PGSCIMAGEC,RaPM),
                                               TblFlt,"DecPM"    ,TblOff(PGSCIMAGEC,DecPM),
                                               TblByt,"class"    ,TblOff(PGSCIMAGEC,class),
                                               TblByt,"VFlag"    ,TblOff(PGSCIMAGEC,VFlag),
                                               TblByt,"MAGFlag"  ,TblOff(PGSCIMAGEC,MAGFlag),
                                               TblFlt,"gmag"     ,TblOff(PGSCIMAGEC,gmag),
                                               TblFlt,"rmag"     ,TblOff(PGSCIMAGEC,rmag),
                                               TblFlt,"imag"     ,TblOff(PGSCIMAGEC,imag),
                                               TblFlt,"vmagerr"  ,TblOff(PGSCIMAGEC,vmagerr),
                                               TblFlt,"bmagerr"  ,TblOff(PGSCIMAGEC,bmagerr),
                                               TblFlt,"gmagerr"  ,TblOff(PGSCIMAGEC,gmagerr),
                                               TblFlt,"rmagerr"  ,TblOff(PGSCIMAGEC,rmagerr),
                                               TblFlt,"imagerr"  ,TblOff(PGSCIMAGEC,imagerr),
                                               0,"end",0);

    } else {
      master_descriptor = table_create_descrip(&master_nrecs,
                                               TblBuf,"REF"      ,TblOff(PGSCIMAGEC,REFNumber),2*MAX_REF,
                                               TblDbl,"ra"       ,TblOff(PGSCIMAGEC,ra),
                                               TblDbl,"dec"      ,TblOff(PGSCIMAGEC,dec),
                                               TblFlt,"Stdmag"   ,TblOff(PGSCIMAGEC,Stdmag),
                                               TblFlt,"color"    ,TblOff(PGSCIMAGEC,color),
                                               TblFlt,"RaPM"     ,TblOff(PGSCIMAGEC,RaPM),
                                               TblFlt,"DecPM"    ,TblOff(PGSCIMAGEC,DecPM),
                                               TblByt,"class"    ,TblOff(PGSCIMAGEC,class),
                                               TblByt,"VFlag"    ,TblOff(PGSCIMAGEC,VFlag),
                                               TblByt,"MAGFlag"  ,TblOff(PGSCIMAGEC,MAGFlag),
                                               0,"end",0);

    }
	} else {

		if (sigmaPMPresent == 0) {

      if (catalogNumber == CATALOG_APASS) {
        master_descriptor = table_create_descrip(&master_nrecs,
                                                 TblBuf,"REFNumber",TblOff(PGSCIMAGEC,REFNumber),2*MAX_REF,
                                                 TblDbl,"ra"       ,TblOff(PGSCIMAGEC,ra),
                                                 TblDbl,"dec"      ,TblOff(PGSCIMAGEC,dec),
                                                 TblFlt,"Stdmag"   ,TblOff(PGSCIMAGEC,Stdmag),
                                                 TblFlt,"color"    ,TblOff(PGSCIMAGEC,color),
                                                 TblFlt,"RaPM"     ,TblOff(PGSCIMAGEC,RaPM),
                                                 TblFlt,"DecPM"    ,TblOff(PGSCIMAGEC,DecPM),
                                                 TblByt,"class"    ,TblOff(PGSCIMAGEC,class),
                                                 TblByt,"VFlag"    ,TblOff(PGSCIMAGEC,VFlag),
                                                 TblByt,"MAGFlag"  ,TblOff(PGSCIMAGEC,MAGFlag),
                                                 TblFlt,"gmag"     ,TblOff(PGSCIMAGEC,gmag),
                                                 TblFlt,"rmag"     ,TblOff(PGSCIMAGEC,rmag),
                                                 TblFlt,"imag"     ,TblOff(PGSCIMAGEC,imag),
                                                 TblFlt,"vmagerr"  ,TblOff(PGSCIMAGEC,vmagerr),
                                                 TblFlt,"bmagerr"  ,TblOff(PGSCIMAGEC,bmagerr),
                                                 TblFlt,"gmagerr"  ,TblOff(PGSCIMAGEC,gmagerr),
                                                 TblFlt,"rmagerr"  ,TblOff(PGSCIMAGEC,rmagerr),
                                                 TblFlt,"imagerr"  ,TblOff(PGSCIMAGEC,imagerr),
                                                 0,"end",0);

      } else {
        master_descriptor = table_create_descrip(&master_nrecs,
                                                 TblBuf,"REFNumber",TblOff(PGSCIMAGEC,REFNumber),2*MAX_REF,
                                                 TblDbl,"ra"       ,TblOff(PGSCIMAGEC,ra),
                                                 TblDbl,"dec"      ,TblOff(PGSCIMAGEC,dec),
                                                 TblFlt,"Stdmag"   ,TblOff(PGSCIMAGEC,Stdmag),
                                                 TblFlt,"color"    ,TblOff(PGSCIMAGEC,color),
                                                 TblFlt,"RaPM"     ,TblOff(PGSCIMAGEC,RaPM),
                                                 TblFlt,"DecPM"    ,TblOff(PGSCIMAGEC,DecPM),
                                                 TblByt,"class"    ,TblOff(PGSCIMAGEC,class),
                                                 TblByt,"VFlag"    ,TblOff(PGSCIMAGEC,VFlag),
                                                 TblByt,"MAGFlag"  ,TblOff(PGSCIMAGEC,MAGFlag),
                                                 0,"end",0);
      }
		} else {
			master_descriptor = table_create_descrip(&master_nrecs,
																							 TblBuf,"REFNumber" ,TblOff(PGSCIMAGEC,REFNumber),2*MAX_REF,
																							 TblDbl,"ra"        ,TblOff(PGSCIMAGEC,ra),
																							 TblDbl,"dec"       ,TblOff(PGSCIMAGEC,dec),
																							 TblFlt,"Stdmag"    ,TblOff(PGSCIMAGEC,Stdmag),
																							 TblFlt,"color"     ,TblOff(PGSCIMAGEC,color),
																							 TblFlt,"RaPM"      ,TblOff(PGSCIMAGEC,RaPM),
																							 TblFlt,"DecPM"     ,TblOff(PGSCIMAGEC,DecPM),
																							 TblFlt,"RaSigmaPM" ,TblOff(PGSCIMAGEC,RaSigmaPM),
																							 TblFlt,"DecSigmaPM",TblOff(PGSCIMAGEC,DecSigmaPM),
																							 TblByt,"class"     ,TblOff(PGSCIMAGEC,class),
																							 TblByt,"VFlag"     ,TblOff(PGSCIMAGEC,VFlag),
																							 TblByt,"MAGFlag"   ,TblOff(PGSCIMAGEC,MAGFlag),
																							 0,"end",0);

		}
	}
  if (master_descriptor == NULL) {
    printf("ERROR: Failed to allocate descriptor for %s\n",master_name);
    return(-1);
  }
  table_loadmap(master_header,master_descriptor);
  sortArrayAlloc = 1000;
  pSortMaster = (PGSCAPASSIMAGE)calloc(sortArrayAlloc,sizeof(GSCAPASSIMAGE));

  while (1) {
    if(ReadMaster(pMaster,master_handle,master_header,master_descriptor,sigmaPMPresent,griPresent,&master_row) == 0) {
      break;
    }
		GetREF(pMaster->REFNumber,masterREF,1,1);
    if (strlen(masterREF) > maxREFLength) {
      maxREFLength = strlen(masterREF);
      if (maxREFLength < (MAX_REF-1)) {
        strcpy(maxREF,masterREF);
      }
    }
    if (pMaster->ra >= 360.0) {
      pMaster->ra -= 360.0;
      ra360count++;
    }
    if (pMaster->ra < 0.0) {
      pMaster->ra += 360.0;
      ranegcount++;
    }


#ifdef NEW_COLOR_CALIBRATION
    if ((pMaster->MAGFlag != 0) &&
        (catalogNumber != CATALOG_APASS) &&
				(catalogNumber != CATALOG_KEPLER) &&
        ((pMaster->MAGFlag < COLOR_BMAG_FOR_JPGMAG) || (pMaster->MAGFlag > COLOR_SKYMAP))) {
      printf("ERROR: Illegal value %d for MAGFlag for %s\n",pMaster->MAGFlag,masterREF);
      exit(-1);
    }
    if ((pMaster->Stdmag == 0.0) && 
        ((catalogNumber == CATALOG_APASS) ||
         (pMaster->MAGFlag == COLOR_VMAG_BMAG_FOR_JPGMAG_FPGMAG) ||
         (pMaster->MAGFlag == COLOR_TYCHO) ||
         (pMaster->MAGFlag == COLOR_SKYMAP)))
    
#else /* NEW_COLOR_CALIBRATION */
      if ((pMaster->Stdmag == 0.0) && 
          ((catalogNumber == CATALOG_APASS) || 
           (pMaster->MAGFlag == (BMAG_FOR_JPGMAG|VMAG_FOR_FPGMAG))))
#endif /* NEW_COLOR_CALIBRATION */
        {
          zeromagCount++;
          if (skipOutput == 0) {
            fprintf(zeromagHandle,"%s\t%f\t%f\t%f\t%f\t%d\t%d\t%d\t%5.1f\t%5.1f\t%5.1f\t%5.1f\n",
                    masterREF,
                    pMaster->ra,
                    pMaster->dec,
                    pMaster->Stdmag,
                    pMaster->color,
                    pMaster->class,
                    pMaster->VFlag,
                    pMaster->MAGFlag,
                    pMaster->RaPM,
                    pMaster->DecPM,
                    pMaster->RaSigmaPM,
                    pMaster->DecSigmaPM);
          }

        } else {
        if ((pMaster->Stdmag < 90.0) && (pMaster->color < 90.0)) {
#ifdef NEW_COLOR_CALIBRATION
          if (catalogNumber != CATALOG_APASS) {
            if (pMaster->MAGFlag == COLOR_JPGMAG_FPGMAG) {
              colorType = COLORINDEX_GSC;
            } else if (pMaster->MAGFlag == COLOR_TYCHO) {
              colorType = COLORINDEX_TYCHO;
            } else {
              colorType = COLORINDEX_NEITHER;
            }
          } else {
            if (pMaster->flag == REF_TYPE_TYCHO2) {
              colorType = COLORINDEX_TYCHO;
            } else {
              colorType = COLORINDEX_GSC;
            }
          }
#else /* NEW_COLOR_CALIBRATION */

          if (catalogNumber != CATALOG_APASS) {
            if ((pMaster->MAGFlag & (JMAG_FOR_JPGMAG|BMAG_FOR_JPGMAG|RMAG_FOR_FPGMAG|VMAG_FOR_FPGMAG)) == 0) {
              colorType = COLORINDEX_GSC;
            } else if ((pMaster->MAGFlag & (JMAG_FOR_JPGMAG|BMAG_FOR_JPGMAG|RMAG_FOR_FPGMAG|VMAG_FOR_FPGMAG)) == (BMAG_FOR_JPGMAG|VMAG_FOR_FPGMAG)) {
              colorType = COLORINDEX_TYCHO;
            } else {
              colorType = COLORINDEX_NEITHER;
            }
          }
#endif /* NEW_COLOR_CALIBRATION */
          allcount[colorType]++;
          
          magBinNumber = (MAGBASE - pMaster->Stdmag)/MAGINC;
          if (magBinNumber < 0) {
            magBinNumber = 0;
          }
          if (magBinNumber > (MAGBINS-2)) {
            magBinNumber = MAGBINS-2;
          }
#if 0
          ++magcount[colorType][magBinNumber];
          avecolor[colorType][magBinNumber] += pMaster->color;
#endif
        }


        tmpRaPM = fabs(pMaster->RaPM);
        tmpDecPM = fabs(pMaster->DecPM);
        tmpPM = sqrt((tmpRaPM*tmpRaPM) + (tmpDecPM*tmpDecPM));
        if (tmpRaPM > maxRaPM) {
          maxRaPM = tmpRaPM;
        }
        if (tmpDecPM > maxDecPM) {
          maxDecPM = tmpDecPM;
        }
        if (tmpPM > 0.05) {
          countPM++;
        }
        if (tmpPM > maxPM) {
          maxPM = tmpPM;
        }


        dec_bin = GetDecBin(pGscBin64,pMaster->dec,"formatgsc");
        if (((master_nrecs+1) % 1000000) == 0) {
          printf("%s RA %f DEC %f dec_bin %d\n",
                 masterREF,
                 pMaster->ra,
                 pMaster->dec,
                 dec_bin);
        }
#if 0
        if (dec_bin == 5769) {
          printf("At dec_bin %d\n",dec_bin);
        }
#endif

        binNumber = GetGSCBin(pGscBin64,pMaster->ra,pMaster->dec,&dec_bin2,&ra_bin,"formatgsc");
        binNumber01 = GetGSCBin(pGscBin01,pMaster->ra,pMaster->dec,&dec_bin01,&ra_bin01,"formatgsc");
        decBinCounts[dec_bin]++;
        gridarray[binNumber01]++;

        if (dec_bin != dec_bin2) {
          printf("ERROR: dec_bin %d not equal to dec_bin2 %d\n",dec_bin,dec_bin2);
          printf("%s\t%f\t%f\t%f\t%f\t%d\t%d\t%d\t%5.1f\t%5.1f\n",
                 masterREF,
                 pMaster->ra,
                 pMaster->dec,
                 pMaster->Stdmag,
                 pMaster->color,
                 pMaster->class,
                 pMaster->VFlag,
                 pMaster->MAGFlag,
                 pMaster->RaPM,
                 pMaster->DecPM);
          return(-1);

        }

#if 0
        printf("%f %f %d %d %d %s\n",pMaster->ra,pMaster->dec,binNumber,dec_bin,ra_bin,masterREF);
#endif
        if (dec_bin < oldDecBin) {
          printf("ERROR: dec_bin %d less than oldDecBin %d\n",dec_bin,oldDecBin);
					GetREF(pOldMaster->REFNumber,oldMasterREF,1,1);

          printf("%s\t%f\t%f\t%f\t%f\t%d\t%d\t%d\t%5.1f\t%5.1f\n",
                 oldMasterREF,
                 pOldMaster->ra,
                 pOldMaster->dec,
                 pOldMaster->Stdmag,
                 pOldMaster->color,
                 pOldMaster->class,
                 pOldMaster->VFlag,
                 pOldMaster->MAGFlag,
                 pOldMaster->RaPM,
                 pOldMaster->DecPM);
          printf("%s\t%f\t%f\t%f\t%f\t%d\t%d\t%d\t%5.1f\t%5.1f\n",
                 masterREF,
                 pMaster->ra,
                 pMaster->dec,
                 pMaster->Stdmag,
                 pMaster->color,
                 pMaster->class,
                 pMaster->VFlag,
                 pMaster->MAGFlag,
                 pMaster->RaPM,
                 pMaster->DecPM);
          exit(-1);
        }
        if (dec_bin > oldDecBin) {
#if 0
          if (dec_bin >= 8364) {
            printf("Line %d oldDecBin %d dec_bin %d\n",__LINE__,oldDecBin,dec_bin);
          }
#endif
          SaveDecBin(outputHandle,indexHandle,pSortMaster,sortArraySize,oldDecBin,radiusArcsec,catalogNumber,placeHolder,griPresent,&savedDecBin,&maxWriteCount,&duplicateCount);
          sortArraySize = 0; 
        }
        if (sortArraySize >= sortArrayAlloc) {
       
          sortArrayAlloc += 1000;
          pSortMaster = realloc(pSortMaster,(sortArrayAlloc * sizeof(GSCAPASSIMAGE)));
          if (pSortMaster == NULL) {
            printf("ERROR pSortMaster realloc failed\n");
          }
        }
        memcpy(&pSortMaster[sortArraySize],pMaster,sizeof(GSCAPASSIMAGE));
        sortArraySize++;
        master_nrecs++;
        oldDecBin = dec_bin;
        memcpy(pOldMaster,pMaster,sizeof(GSCAPASSIMAGE));
      }
  }
  SaveDecBin(outputHandle,indexHandle,pSortMaster,sortArraySize,oldDecBin,              radiusArcsec,catalogNumber,placeHolder,griPresent,&savedDecBin,&maxWriteCount,&duplicateCount);
  sortArraySize = 0;
  SaveDecBin(outputHandle,indexHandle,pSortMaster,sortArraySize,(pGscBin64->dec_bins-1),radiusArcsec,catalogNumber,placeHolder,griPresent,&savedDecBin,&maxWriteCount,&duplicateCount);

  if (gmtHandle != NULL) {
    int binIndex01;
    PBININDEX pBinIndex01;
    int raBinIndex01;
    int decBinIndex01;
    double raval;
    double decval;
    double raout;
    double decout;
    for (binIndex01 = 0; binIndex01 < pGscBin01->total_gsc_bins; binIndex01++) {
      pBinIndex01 = GetSubbins(pGscBin01,binIndex01,&raBinIndex01,&decBinIndex01,"formatgsc");
      raval = (360.0 * raBinIndex01)/(pBinIndex01->numBins) + (180.0/(pBinIndex01->numBins));
      decval = (decBinIndex01 * pGscBin01->bin_size) - 90.0 +  (pGscBin01->bin_size/2.0);
      if ((raval < 0) || (raval > 360.0)) {
        printf("raval error\n");
      }
      if ((decval < -90.0) || (decval > 90.0)) {
        printf("decval error\n");
      }
      raout = raval;
      decout = decval;
      fprintf(gmtHandle,"%f %f %d\n",360.0 - raout,decout,gridarray[binIndex01]);
                              
    
    }
    

  }


  if (master_header != NULL) {
    table_hdrfree(master_header);
  }
  if (master_handle != NULL) {
    Close(master_handle);
  }
  if (master_descriptor != NULL) {
    Free(master_descriptor);
  }
  if (master_row != NULL) {
    table_rowfree(master_row);
  }

  if (skipOutput == 0) {
    Close(outputHandle);
    Close(indexHandle);
    fclose(zeromagHandle);
  }
  if (pGscBin64->pBinMasterIndex != NULL) {
    free(pGscBin64->pBinMasterIndex);
  }
  if (mergeHandle != NULL) {
    fclose(mergeHandle);
  }

  time(&curTime);
  curTime -= startTime;
  for (dec_bin = 0; dec_bin < pGscBin64->dec_bins; dec_bin++) {
    if (decBinCounts[dec_bin] > 0) {
#if 1
      printf("dec_bin %d count %d\n",dec_bin,decBinCounts[dec_bin]);
#endif
      totalBinCount += decBinCounts[dec_bin];

      if (decBinCounts[dec_bin] > maxDecBin) {
        maxDecBin = decBinCounts[dec_bin];
      }
    }
  }

  printf("Execution Time: %d seconds for %d records; zeromag %d; max dec bin size %d max ra bin size %d totalBins %d, maxRaPM %5.1f, maxDecPM %5.1f, maxPM %5.1f countPM %d maxREFLength %d duplicateCount %d for %s ra360count %d ranegcount %d\n",curTime,master_nrecs,zeromagCount,maxDecBin,maxWriteCount,totalBinCount,maxRaPM,maxDecPM,maxPM,countPM,maxREFLength,duplicateCount,maxREF,ra360count,ranegcount);


  /* Total up the bins */
  for (colorType = 0; colorType < COLORINDEX_MAX; colorType++) {
    maxcount[colorType] = 0;
    for (magBinNumber = 0; magBinNumber < (MAGBINS-1); magBinNumber++) {
      magcount[colorType][MAGBINS-1] += magcount[colorType][magBinNumber];
      avecolor[colorType][MAGBINS-1] += avecolor[colorType][magBinNumber];
      if (magcount[colorType][magBinNumber] > maxcount[colorType]) {
        maxcount[colorType] = magcount[colorType][magBinNumber]; 
      }
    }
  }

  for (colorType = 0; colorType < COLORINDEX_MAX; colorType++) {
    for (magBinNumber = 0; magBinNumber < MAGBINS; magBinNumber++) {
      if (magcount[colorType][magBinNumber] > 0) {
        avecolor[colorType][magBinNumber] = avecolor[colorType][magBinNumber]/(1.0 * magcount[colorType][magBinNumber]);
        magnorm[colorType][magBinNumber] = (1.0 * magcount[colorType][magBinNumber])/(1.0 * maxcount[colorType]);
      }
    }
    magnorm[colorType][MAGBINS-1] = 0.0;
  }
  for (colorType = 0; colorType < COLORINDEX_MAX; colorType++) {
    if (allcount[colorType] == 0) {
      continue;
    }
    for (magBinNumber = 0; magBinNumber < MAGBINS; magBinNumber++) {
      printf("Type %d Mag %4.1f to %4.1f Count %10d NormCount %5.3f avecolor %5.2f\n",
             colorType,
             MAGBASE - (MAGINC * magBinNumber),
             MAGBASE - (MAGINC * (magBinNumber+1)),
             magcount[colorType][magBinNumber],
             magnorm[colorType][magBinNumber],
             avecolor[colorType][magBinNumber]);
    }                   
  }
  for (index = 0; index < 17; index++) {
    printf("Case %2d, Count %10d\n",index,casetable[index]);
  }


  if (gridarray != NULL) {
    free(gridarray);
  }

  if (decBinCounts != NULL) {
    free(decBinCounts);
  }
  if (pSortMaster != NULL) {
    free(pSortMaster);
  }
  if (gmtHandle != NULL) {
    fclose(gmtHandle);
  }


  return(EXIT_SUCCESS);
}
