// Copyright the President and Fellows of Harvard College.
// Licensed under the MIT License

/* 
 * idstats.c
 *
 *   Compute ID table statistics in accordance with summary_table.csh, but only for the released region
 *
 *
 *  cc -ggdb -O2   -DLinux -DSTDC_HEADERS=1 -DCONFIG_BROKETS -DHAVE_DIRENT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_MEMCPY=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_FCNTL_H=1 -DHAVE_ALLOCA_H=1 -DHAVE_FLOAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MEMCHR=1 -DHAVE_STRCHR=1 -DHAVE_STRERROR=1 -DHAVE_STRUCT_TM_TM_ZONE=1 -DHAVE_TM_ZONE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/include/mysql -I/dasch/install/include idstats.c pipelineutils.a -L /dasch/install/lib -lm  -L/usr/lib${lib64}/mysql  -lmysqlclient -ldl -pthread    -ltable -lutil  -lwcs -lgd  -o idstats
 *
 *
 *      NOTE: all files implied to be in the $DASCH_INGEST directory
 
    idstats -i id_table_gsc_2014_12_22.db -o id_gscDR4.db -q gsc2.3.2 -r rms_gscDR4.db
    idstats -i id_table_kepler_2012_07_19.db -o id_keplerDR4.db -q kepler -r rms_keplerDR4.db
    idstats -i id_table_apass_2015_01_24.db -o id_apassDR4.db -q apass -r rms_apassDR4.db

 *
 * ID tables generated by update_summary
 *

    idstats -i id_table_gsc_2015_06_07.db -o id_gscDR4a.db -q gsc2.3.2 -r rms_gscDR4a.db
    idstats -i id_table_kepler_2012_07_19.db -o id_keplerDR4a.db -q kepler -r rms_keplerDR4a.db
    idstats -i id_table_apass_2015_06_07.db -o id_apassDR4a.db -q apass -r rms_apassDR4a.db
 *
 * ID tables generated by update_summary2
 *
    idstats -i id_gsc_2017_11_17.db -o id_gscDR4.db -q gsc2.3.2 -r rms_gscDR4.db
    idstats -i id_kepler_2017_11_17.db -o id_keplerDR4.db -q kepler -r rms_keplerDR4.db
    idstats -i id_apass_2015_06_04.db -o id_apassDR4.db -q apass -r rms_apassDR4.db

 *
 * Sep 16, 2013 Edward J. Los - Initial version
 * Sep 26, 2013 Edward J. Los - Add a histogram of ngood as a function of year.
 * Jun 17, 2015 Edward J. Los - Reject unauthorized bins first to get a count of the total lightcurves in the release
 *
 */

#include <math.h>
#include <time.h>
#include "table.h"
#include "pipelineutils.h"
#include "libwcs/fitsfile.h"
#include "libwcs/wcs.h"

#define MAX_BUFFER 512
#define MAX_MAG 20
#define ALL_MAG  0   /* The index to total all magnitudes */
#if 1
#define MAX_RMS 1000 /* Divide by this number to get the actual median RMS */
#define MAX_RMS_KEPLER 100
#else
#define MAX_RMS 1000000 /* Divide by this number to get the actual median RMS */
#define MAX_RMS_KEPLER 10000
#endif
#define MAX_NPOINTS 10000
#define ALL_NPOINTS     0
typedef struct _idtable {
	double ra;
	double dec;
	double clip_median_local;
	double clip_rms_local;
	int clip_ngood;
	int nburst3;
	int npoints;
} IDTABLE,*PIDTABLE;

extern char *catalogText[MAX_CATALOG_NUMBER];

int ReadIdtable(PIDTABLE pIdtable,
               File idtable_handle,
               TableHead idtable_header,
               TblDescriptor idtable_descriptor,
               TableRow* idtable_row)
{
  *idtable_row = table_rowget(idtable_handle,idtable_header,*idtable_row,NULL,NULL,0);
  if (*idtable_row == NULL) {
    return(0);
  }
  if (!table_loadrow(idtable_handle,idtable_header,*idtable_row,idtable_descriptor,(char *)pIdtable)) {
    printf("ERROR: Read Idtable table_loadrow failed\n");
    return(0);
  }
  return(1);
}



int main(int argc,char *argv[])
{
  int nvals;
  char *argstr;
  char cmdchar;
  int errorFlag = 0;
	int verbose = 0;
	char source[MAX_BUFFER];
	FILE *outHandle = NULL;
  FILE *rmsHandle = NULL;

  File idtable_handle = NULL;
  char idtable_name[MAX_BUFFER];
	char idtable_fullname[MAX_BUFFER];
	char outfile[MAX_BUFFER];
	char outfile_fullname[MAX_BUFFER];
	char rmsfile[MAX_BUFFER];
	char rmsfile_fullname[MAX_BUFFER];
	char qualifier[MAX_BUFFER];
  TableHead idtable_header = NULL;
  PIDTABLE idtable_table = NULL;
  PIDTABLE tmp_idtable_table = NULL;
  int idtable_allocation = 0;
  int idtable_nrecs = 0;
	long long idtable_total_nrecs = 0;
  int idtable_blend_nrecs = 0;
  int idtable_index;
  int idtable_index2;
  IDTABLE idtable_record;
  PIDTABLE pIdTable = &idtable_record;
  PIDTABLE pIdTable2 = NULL;
  TblDescriptor idtable_descriptor = NULL;
  TableRow idtable_row = NULL;
  time_t startTime;
  time_t curTime;
	long long good_records = 0;
	long long unauthorizedCount = 0;
	long long low_ngood_count = 0;
  char *ingestDirectory;
	int releaseField;
	long long countTable[MAX_MAG+1];
	int countIndex;
	int* rmsTable[MAX_MAG+1];
	int* npointsTable[MAX_MAG+1];
	int rmsIndex;
	int* rmsPtr;
	int* npointsPtr;
	int rmsCounter;
	int npointsCounter;
	int medianCount;
	double medianValue;
	int medianNpoints;
	long long nburst3RejectCount = 0;
	int nburst3Count[MAX_MAG+1];
	long long nburst3Total[MAX_MAG+1];
	double normnburst3;
	int catalogNumber = 0;
	int npointsIndex;
  int maxRMSValue = MAX_RMS;

	memset(countTable,0,sizeof(countTable));
	memset(rmsTable,0,sizeof(rmsTable));
	memset(nburst3Count,0,sizeof(nburst3Count));
	memset(nburst3Total,0,sizeof(nburst3Total));
	memset(npointsTable,0,sizeof(npointsTable));



	npointsTable[ALL_MAG] = (int *)calloc(MAX_NPOINTS+1,sizeof(int));
	if (npointsTable[ALL_MAG] == NULL) {
		printf("ERROR: Failure to allocate npointsTable at index %d\n",ALL_MAG);
		exit(-1);
	}
	source[0] = 0;
	idtable_name[0] = 0;
	outfile[0]  = 0;
	qualifier[0] = 0;
  rmsfile[0] = 0;

  /* Loop through the arguments */
  for (argv++; --argc > 0; argv++) {
    argstr = *argv;
    /* Decode arguments */
    if (argstr[0] != '-') {
      /* This is a stray argument */
      errorFlag = 1;
      fprintf(stderr,"ERROR: argument %s does not have a qualifier\n",argstr);
    } else {
      while ((cmdchar = *++argstr) != 0) {
        switch(cmdchar) {
        case 'o': /* output file name */
        case 'O':
          argc--;
          if (argc < 1) {
            fprintf(stderr,"ERROR: Insufficient arguments for -%c\n",cmdchar);
            errorFlag = 1;
          } else {
            strncpy(outfile,*++argv,MAX_BUFFER-2);
            if (strlen(*argv) >= MAX_BUFFER-2) {
              fprintf(stderr,"ERROR: MAX_BUFFER too small for %s\n",*argv);
            }
          }
          break;


        case 'r': /* rms histogram name */
        case 'R':
          argc--;
          if (argc < 1) {
            fprintf(stderr,"ERROR: Insufficient arguments for -%c\n",cmdchar);
            errorFlag = 1;
          } else {
            strncpy(rmsfile,*++argv,MAX_BUFFER-2);
            if (strlen(*argv) >= MAX_BUFFER-2) {
              fprintf(stderr,"ERROR: MAX_BUFFER too small for %s\n",*argv);
            }
          }
          break;

        case 'i': /* id table name */
        case 'I':
          argc--;
          if (argc < 1) {
            fprintf(stderr,"ERROR: Insufficient arguments for -%c\n",cmdchar);
            errorFlag = 1;
          } else {
            strncpy(idtable_name,*++argv,MAX_BUFFER-2);
            if (strlen(*argv) >= MAX_BUFFER-2) {
              fprintf(stderr,"ERROR: MAX_BUFFER too small for %s\n",*argv);
            }
          }
          break;

				case 'q': /* Catalog and file name qualifier */
        case 'Q':
          argc--;
          if (argc < 1) {
            fprintf(stderr,"ERROR: Insufficient arguments for -%c\n",cmdchar);
            errorFlag = 1;
          } else {
            catalogNumber = GetCatalogNumber(*++argv);
            if (catalogNumber < 0) {
              fprintf(stderr,"ERROR: Illegal catalog name %s\n",*argv);
              errorFlag = 1;
            } else {
              strcpy(source,*argv);
              if (catalogNumber > 0) {
                strcpy(qualifier,*argv);
              }
            }
          }
          break;

 


        case 'v': /* verbose */
        case 'V':
          verbose = 1;
          break;


        default:
          fprintf(stderr,"ERROR:  unknown command -%c\n",cmdchar);
          errorFlag = 1;

        }
        
      }

    }
  }
	if (idtable_name[0] == 0) {
		printf("ERROR: Not id table name input\n");
		errorFlag = 1;
	}

  if (catalogNumber == CATALOG_KEPLER) {
    maxRMSValue = MAX_RMS_KEPLER;
  }

	rmsTable[ALL_MAG] = (int *)calloc(maxRMSValue+1,sizeof(int));
	if (rmsTable[ALL_MAG] == NULL) {
		printf("ERROR: Failure to allocate rmsTable at index %d\n",ALL_MAG);
		exit(-1);
	}


  time(&startTime);

  ingestDirectory = getenv("DASCH_INGEST");
  if (ingestDirectory == NULL) {
    fprintf(stderr,"ERROR: DASCH_INGEST is not defined\n");
    return(-1);
  }

	printf("idtable of %s %s RELEASE_LEVEL %d maxRMSValue %d macatalog %s outfile %s rmsfile %s\n",__DATE__,__TIME__,RELEASE_LEVEL,maxRMSValue,catalogText[catalogNumber],outfile,rmsfile);

	strcpy(idtable_fullname,ingestDirectory);
	strcat(idtable_fullname,"/");
	strcat(idtable_fullname,idtable_name);


	idtable_handle = Open(idtable_fullname,"r");
	if (idtable_handle == NULL) {
		fprintf(stderr,"ERROR: Failed to find the idtable file %s\n",idtable_fullname);
		errorFlag = 1;
	} else {
		fprintf(stderr,"Found idtable file %s\n",idtable_fullname);
	}

	idtable_header = table_header(idtable_handle,TABLE_PARSE);
	if (idtable_header == NULL) {
		fprintf(stderr,"ERROR: Failed to read header for %s\n",idtable_fullname);
		errorFlag = 1;
	}
	idtable_descriptor = table_create_descrip(&idtable_nrecs,
																						TblDbl,"ra",TblOff(PIDTABLE,ra),
																						TblDbl,"declination",TblOff(PIDTABLE,dec),
																						TblDbl,"clip_median_local",TblOff(PIDTABLE,clip_median_local),
																						TblDbl,"clip_rms_local",TblOff(PIDTABLE,clip_rms_local),
																						TblInt,"clip_ngood",TblOff(PIDTABLE,clip_ngood),
																						TblInt,"nburst3",TblOff(PIDTABLE,nburst3),
																						TblInt,"npoints",TblOff(PIDTABLE,npoints),
																						0,"end",0);
	if (idtable_descriptor == NULL) {
		fprintf(stderr,"ERROR: Failed to allocate descriptor for %s\n",idtable_fullname);
		errorFlag = 1;
	}

	if (errorFlag != 0) {
		printf("Usage: idstats -i <input file> -o <output file> -q <catalog>\n");
		exit(-1);
	}

	if (outfile[0] != 0) {
		strcpy(outfile_fullname,ingestDirectory);
		strcat(outfile_fullname,"/");
		strcat(outfile_fullname,outfile);
		outHandle = fopen(outfile_fullname,"wt");
		if (outHandle == NULL) {
			printf("ERROR: failed to open outfile %s\n",outfile_fullname);
		} else {
			printf("opened output file %s\n",outfile_fullname);
			fprintf(outHandle,"minmag\tmaxmag\tcount\tmedian\tnormnburst3\tcatalogNumber\tnpoints\n");
			fprintf(outHandle,"------\t------\t-----\t------\t-----------\t-------------\t-------\n");
		}
	}

	if (rmsfile[0] != 0) {
		strcpy(rmsfile_fullname,ingestDirectory);
		strcat(rmsfile_fullname,"/");
		strcat(rmsfile_fullname,rmsfile);
		rmsHandle = fopen(rmsfile_fullname,"wt");
		if (rmsHandle == NULL) {
			printf("ERROR: failed to open rmsfile %s\n",rmsfile_fullname);
		} else {
			printf("opened rmsput file %s\n",rmsfile_fullname);
			fprintf(rmsHandle,"minmag\tmaxmag\tclip_rms_local\tcount\tcatalogNumber\n");
			fprintf(rmsHandle,"------\t------\t--------------\t-----\t-------------\n");
		}
	}



	table_loadmap(idtable_header,idtable_descriptor);
	idtable_total_nrecs = 0;
	while(1) {
		memset(pIdTable,0,sizeof(IDTABLE));
		if(ReadIdtable(pIdTable,idtable_handle,idtable_header,idtable_descriptor,&idtable_row) == 0) {
			break;
		}
		idtable_total_nrecs++;
#if 0
		if (idtable_total_nrecs == 1739) {
			printf("At idtable_total_nrecs %lld\n",idtable_total_nrecs);
		}
#endif
		if (CheckAuthorization("none",pIdTable->ra,pIdTable->dec,&releaseField) == 0) {
			unauthorizedCount++;
			continue;
		}
		if (pIdTable->clip_ngood < 10) {
			low_ngood_count++;
			continue;
		}
		countIndex = pIdTable->clip_median_local;
		if ((countIndex < 1) || (countIndex > MAX_MAG)) {
			countIndex = MAX_MAG;
		}
		countTable[ALL_MAG]++;
		rmsIndex = (1.0*maxRMSValue)*pIdTable->clip_rms_local;
		if (rmsIndex > maxRMSValue) {
			rmsIndex = maxRMSValue;
		} else if (rmsIndex < 0) {
			rmsIndex = 0;
		}
		rmsPtr = rmsTable[ALL_MAG];
		rmsPtr[rmsIndex]++;

		countTable[countIndex]++;
		if (rmsTable[countIndex] == NULL) {

			rmsTable[countIndex] = (int *)calloc(maxRMSValue+1,sizeof(int));
			if (rmsTable[countIndex] == NULL) {
				printf("ERROR: Failure to allocate rmsTable at index %d\n",countIndex);
				exit(-1);
			}
		}
		rmsPtr = rmsTable[countIndex];
		rmsPtr[rmsIndex]++;
		if (pIdTable->nburst3 >= 0) {
			nburst3Count[countIndex]++;
			nburst3Total[countIndex] += pIdTable->nburst3;
			nburst3Count[ALL_MAG]++;
			nburst3Total[ALL_MAG] += pIdTable->nburst3;
		} else {
			nburst3RejectCount++;
		}
		npointsIndex = pIdTable->npoints;
		if (npointsIndex > MAX_NPOINTS) {
			npointsIndex = MAX_NPOINTS;
		} else if (npointsIndex < 0) {
			npointsIndex = 0;
		}

		if (npointsTable[countIndex] == NULL) {

			npointsTable[countIndex] = (int *)calloc(MAX_NPOINTS+1,sizeof(int));
			if (npointsTable[countIndex] == NULL) {
				printf("ERROR: Failure to allocate npointsTable at index %d\n",countIndex);
				exit(-1);
			}
		}
		npointsPtr = npointsTable[countIndex];
		npointsPtr[npointsIndex]++;


		good_records++;
	}

	time(&curTime);
	curTime -= startTime;
	printf(" mag    count  median  normalized       median\n");
	printf("                 rms    nburst3         npoints\n");
	for (countIndex = MAX_MAG; countIndex >= 0 ; countIndex--) {
		if (countTable[countIndex] != 0) {
		
			/* Now total everything up until we get to the median */
			medianCount = countTable[countIndex]/2;
			rmsCounter = 0;
			rmsPtr = rmsTable[countIndex];
			for (rmsIndex = 0; rmsIndex < maxRMSValue; rmsIndex++) {
				rmsCounter += rmsPtr[rmsIndex];
				if (rmsCounter >= medianCount) {
					medianValue = 1.0*rmsIndex/(1.0*maxRMSValue);
					break;
				}
			}
			npointsCounter = 0;
			npointsPtr = npointsTable[countIndex];
			for (npointsIndex = 0; npointsIndex < MAX_NPOINTS; npointsIndex++) {
				npointsCounter += npointsPtr[npointsIndex];
				if (npointsCounter >= medianCount) {
					medianNpoints = npointsIndex;
					break;
				}
			}
			

			normnburst3 = 0.0;
			if (nburst3Count[countIndex] > 0) {
				normnburst3 = (1.0*nburst3Total[countIndex])/(1.0*nburst3Count[countIndex]);
			}

			if (countIndex == ALL_MAG) {
				printf("%2d %2d %7lld %8.6f %9.7f %4d\n",3,19, countTable[countIndex],medianValue,normnburst3,medianNpoints);
			} else {
				printf("%2d %2d %7lld %8.6f %9.7f %4d\n",countIndex,countIndex+1, countTable[countIndex],medianValue,normnburst3,medianNpoints);
				fprintf(outHandle,"%2d\t%2d\t%7d\t%8.6f\t%9.7f\t%d\t%d\n",countIndex,countIndex+1,countTable[countIndex],medianValue,normnburst3,catalogNumber,medianNpoints);
        if (rmsHandle != NULL) {
          for (rmsIndex = 0; rmsIndex < maxRMSValue; rmsIndex++) {
            rmsCounter += rmsPtr[rmsIndex];
            fprintf(rmsHandle,"%2d\t%2d\t%f\t%d\t%d\n",countIndex,countIndex+1,((1.0*rmsIndex)/(1.0*maxRMSValue)),rmsPtr[rmsIndex],catalogNumber);
          }
        }

			}

		}
	}

	printf("Read %lld records, low ngood %lld unauthorized %lld kept %lld nburst3 Reject %lld in %d seconds\n",idtable_total_nrecs,low_ngood_count,unauthorizedCount,good_records,nburst3RejectCount,curTime);
	if (outHandle != NULL) {
		fclose(outHandle);
	}
	if (rmsHandle != NULL) {
		fclose(rmsHandle);
	}

	return(0);
}
