#!/bin/csh
# Copyright the President and Fellows of Harvard College.
# Licensed under the MIT License

# This script adds a row of dashes to a tab-spaced file generated by MySQL to produce a starbase table
#
#  if infile.txt is the output of Mysql "SHOW TABLE STATUS;"
#  then ./makestarbase.csh infile.txt outfile.txt
#       row '/mag.*/' < los1.tmp | column Rows | statstable counts the rows
#
#
#
set inputfile = $1
set outputfile = $2
#echo "argv is $#argv"
if ($#argv !=  2) then
    echo "usage: insertdasch.csh <input tab-spaced file> <output starbase table>
    exit
endif 
set columns = `cat $inputfile | gawk 'NR==1'`
#echo "Header line is $columns"
echo $columns >! $outputfile.header
cat $outputfile.header | sed 's/[A-Z,a-z,_,0-9]/-/g'  >> $outputfile.header
cat $outputfile.header | sed 's/ /\t/g' >! $outputfile
cat $inputfile | gawk 'NR>1' >> $outputfile
rm $outputfile.header
