#!/bin/csh
# Copyright the President and Fellows of Harvard College.
# Licensed under the MIT License

#  
#  This script creates plots for the *_drad.db files generated by
#  the filterblended changes for V3.5.2
#
#  Feb 18, 2009 Edward J. Los - Initial version
#  Feb 22, 2009 Edward J. Los - Modify to use <plate>_dmagcor.db
# 
#  Usage ./plot_distortion.csh  <basename> <series>
#             <basename> is the file prefix
#             <series> is the series, or a string of multiple series
#
set imagelist = $1
set qualifier = ""
if ($#argv == 2) then
    set qualifier = "2"
endif

date
source ${DASCH_SCRIPTS}/initgmt
cd ${DASCH_INGEST}
set listroot = $imagelist:t
pwd
echo "Processing ${DASCH_SCRIPTS}/$listroot"

foreach plate ( `cat ${DASCH_SCRIPTS}/$listroot` ) 
  echo "Processing plate ${plate}"
  set script_output = `$DASCH_SCRIPTS/getlocation  $plate`
  set plate_scale = `echo "$script_output" | gawk '{print $4}'` 
  #set filename = "${plate}_drad.db"
  set filename = "${plate}_dmagcor.db"
  echo "Filename: ${filename} Qualifier ${qualifier} argv $#argv"

  column -b -i ${filename} ix iy drad_bin_count${qualifier} > plot${qualifier}_${plate}_drad_bin_count.txt
  minmax plot${qualifier}_${plate}_drad_bin_count.txt
  xyz2grd plot${qualifier}_${plate}_drad_bin_count.txt -R0/50/0/50 -I1.0/1.0 -Gplot${qualifier}_${plate}_drad_bin_count.grd
  grdview plot${qualifier}_${plate}_drad_bin_count.grd -JX4i/4i  -JZ2i -E225/30 -B10:"X ${plate}":/10:"Y":/20:"Z drad_bin_count${qualifier}":WSZne >! plot${qualifier}_${plate}_drad_bin_count.ps
  
  column -i ${filename} ix iy draMedian${qualifier} pixels | compute pixels=draMedian${qualifier}/${plate_scale} | column -b ix iy pixels > plot${qualifier}_${plate}_draMedian.txt
  minmax plot${qualifier}_${plate}_draMedian.txt
  xyz2grd plot${qualifier}_${plate}_draMedian.txt -R0/50/0/50 -I1.0/1.0 -Gplot${qualifier}_${plate}_draMedian.grd
  grdview plot${qualifier}_${plate}_draMedian.grd -JX4i/4i  -JZ2i -E225/30 -B10:"X ${plate}":/10:"Y":/1:"Z draMedian${qualifier} pixels":WSZne >! plot${qualifier}_${plate}_draMedian.ps
  
  column -i ${filename} ix iy ddecMedian${qualifier} pixels | compute pixels=ddecMedian${qualifier}/${plate_scale} | column -b ix iy pixels > plot${qualifier}_${plate}_ddecMedian.txt
  minmax plot${qualifier}_${plate}_ddecMedian.txt
  xyz2grd plot${qualifier}_${plate}_ddecMedian.txt -R0/50/0/50 -I1.0/1.0 -Gplot${qualifier}_${plate}_ddecMedian.grd
  grdview plot${qualifier}_${plate}_ddecMedian.grd -JX4i/4i  -JZ2i -E225/30 -B10:"X ${plate}":/10:"Y":/1:"Z ddecMedian${qualifier} pixels":WSZne >! plot${qualifier}_${plate}_ddecMedian.ps
  
  
  row "draRMS${qualifier}<90.0" < ${filename} |column   ix iy draRMS${qualifier} pixels | compute pixels=draRMS${qualifier}/${plate_scale} | column -b ix iy pixels > plot${qualifier}_${plate}_draRMS.txt
  minmax plot${qualifier}_${plate}_draRMS.txt
  xyz2grd plot${qualifier}_${plate}_draRMS.txt -R0/50/0/50 -I1.0/1.0 -Gplot${qualifier}_${plate}_draRMS.grd
  grdview plot${qualifier}_${plate}_draRMS.grd -JX4i/4i  -JZ2i -E225/30 -B10:"X ${plate}":/10:"Y":/1:"Z draRMS${qualifier} pixels":WSZne >! plot${qualifier}_${plate}_draRMS.ps

  row "ddecRMS${qualifier}<90.0" < ${filename} | column   ix iy ddecRMS${qualifier} pixels | compute pixels=ddecRMS${qualifier}/${plate_scale} | column -b ix iy pixels > plot${qualifier}_${plate}_ddecRMS.txt
  minmax plot${qualifier}_${plate}_ddecRMS.txt
  xyz2grd plot${qualifier}_${plate}_ddecRMS.txt -R0/50/0/50 -I1.0/1.0 -Gplot${qualifier}_${plate}_ddecRMS.grd
  grdview plot${qualifier}_${plate}_ddecRMS.grd -JX4i/4i  -JZ2i -E225/30 -B10:"X ${plate}":/10:"Y":/1:"Z ddecRMS${qualifier} pixels":WSZne >! plot${qualifier}_${plate}_ddecRMS.ps


  rm plot${qualifier}_${plate}_drad_bin_count.txt
  rm plot${qualifier}_${plate}_draMedian.txt
  rm plot${qualifier}_${plate}_draRMS.txt
  rm plot${qualifier}_${plate}_ddecMedian.txt
  rm plot${qualifier}_${plate}_ddecRMS.txt
  rm plot${qualifier}_${plate}_drad_bin_count.grd
  rm plot${qualifier}_${plate}_draMedian.grd
  rm plot${qualifier}_${plate}_draRMS.grd
  rm plot${qualifier}_${plate}_ddecMedian.grd
  rm plot${qualifier}_${plate}_ddecRMS.grd

end

date
