% Copyright the President and Fellows of Harvard College.
% Licensed under the MIT License

% smooth the color-term over plate series, to calculate the average color-term
%    Jan 31, 2009  Sumin Tang    Initial version
%    Mar  4, 2009  Edward J. Los Updated for octave
% ----------------
%
%  Takes files generated by ingest_colorterm.csh
%
% -- Output file: smoothed_colorterm_bin2.txt, 4 columns, color-term, color-term err, flag, smoothed color-term, 
%                  in the same order as colorterm_bin2.txt 
%                 a fig showing the smoothed average, on top of the individual color-term

clear

startTime = time();
debugSuffix = "";
qualifier = "";
catalogbin = getenv("DASCH_CATALOGBIN");
printf("catalogbin is %s\n",catalogbin);
if (length(catalogbin) < 1) 
  exit;
endif
do_plots = getenv("DASCH_PLOT");
printf("do_plots is %s\n",do_plots);
if (length(do_plots) < 1) 
  exit;
endif
num_bins = getenv("DASCH_NUMBINS");
printf("num_bins is %s\n",num_bins);
if (length(num_bins) < 1) 
  exit;
endif
listfile = [catalogbin '/' char(argv()(1))];
%listfile = [catalogbin '/color_test_colorterm.db'];
%listfile = [catalogbin '/color_colorterm.db'];

printf("Colorterm file is %s qualifier is %s\n",listfile,qualifier);

fid = fopen(listfile,'rt');
iii = 0;
totalLines = 0;
badflags = 0;
% skip the header 
txt = fgetl(fid);
txt = fgetl(fid);
seriesString = cell(1);
colorcount(50,9) = 0;
mosaic = cell(1);

while ((txt = fgetl(fid)) != -1)
   error = 0;
   totalLines++;    
   iii++;

   [mosaic_txt,series_txt,plateNumber_txt,spatial_bin_txt,colorterm_txt,errorcolor_txt,colorflag_txt,count] = sscanf(txt,"%s %s %d %d %f %f %d","C");
   if (count != 7)
     printf("Line %d count %d\n",totalLines,count);
     error = 1;
   endif
%  if (colorflag_txt != 2)
%    badflags++;
%    error = 1;
%  endif
   if (error == 0)  
     seriesIndex = find(strcmp(seriesString,series_txt));
     if (length(seriesIndex) == 0) 
       if (iii == 1)
         seriesString(1) = series_txt;
       else
          seriesString(length(seriesString)+1) = series_txt;
       endif
       seriesIndex = length(seriesString);
     endif
     nextval = colorcount(seriesIndex,spatial_bin_txt)++ + 1;
     colorterm(seriesIndex,spatial_bin_txt,nextval) = colorterm_txt;
     errorcolor(seriesIndex,spatial_bin_txt,nextval) = errorcolor_txt;
     colorflag(seriesIndex,spatial_bin_txt,nextval) = colorflag_txt;
     plateNumber(seriesIndex,spatial_bin_txt,nextval) = plateNumber_txt;
     mosaic(seriesIndex,spatial_bin_txt,nextval) = mosaic_txt;
     
   else 
     iii--;
   endif


endwhile

fclose(fid);

ks = length(seriesString);
for iseries = 1:ks
  for bin = 1:9 
    printf("Processing series %s, bin %d\n",seriesString(iseries),bin);
    ksize2 = colorcount(iseries,bin);
    if (ksize2 > 2)
      clear mycolor;
      clear mycolors;
      mycolor(1:ksize2) = colorterm(iseries,bin,1:ksize2);
      mediancolor(iseries)=median(mycolor);
      stdcolor(iseries)=std(mycolor);
        
      iy=find(abs(mycolor-mediancolor(iseries))<4*stdcolor(iseries));
      stdcolor2(iseries)=std(mycolor(iy));
      clear colors;
      if ksize2>20
        colors=smooth(1:ksize2,mycolor,0.5,'rlowess'); 
      elseif stdcolor2(iseries)<0.15
        colors(1:ksize2)=mediancolor(iseries);
      else
        colors(1:ksize2)=mycolor;
      end
      iy2=find(abs(mycolor-mediancolor(iseries))>5*stdcolor2(iseries));
      colors(iy2)=mycolor(iy2);
        
      mycolors(1:ksize2)=colors;

      printf("mediancolor %f stdcolor2 %f for  series %s, bin %d\n",mediancolor(iseries),stdcolor2(iseries),seriesString(iseries),bin);


% Write a smoothed color file for each plate
      for iplate = 1:ksize2
          listentry = char(mosaic(iseries,bin,iplate));
          outfile = [catalogbin '/' listentry qualifier '_a'  num2str(bin)  '.smoothcolorterm.txt'];
 %        printf("Writing %s with %d points\n",outfile,ksize2);
          fid = fopen(outfile,'w');
          if (fid == -1)
            printf("Failed to open file %s for writing\n",outfile); 
          endif 
          fprintf(fid,'%1.3f  %1.3f  %1.0f  %1.3f \n',colorterm(iseries,bin,iplate),errorcolor(iseries,bin,iplate),colorflag(iseries,bin,iplate),mycolors(iplate));
          fclose(fid);
      end
      figure(1,'visible','off');
      h = plot(1:ksize2,mycolor,'g+','markersize',9,1:ksize2,mycolors,'r+','markersize',9);
      xlabel('Plate Sequence','Fontsize',18);
      ylabel('colorterm','Fontsize',18);
      seriesEntry = char(seriesString(iseries));
      title([seriesEntry qualifier ' bin ' num2str(bin) ' colorterm'],'Fontsize',18);
      print([catalogbin '/colorterm_' seriesEntry qualifier '_a' num2str(bin) '.eps']);
      close

    endif
  end % bin loop

end %series loop
    
